import StabilizerBW.SqrtPi.Clifford
import StabilizerBW.SqrtPi.OplusCost

/-!
# T4* — The grade-`0` ⊆ Clifford converse at a single qubit

The continuation asked for the converse `grade2obj a = 0 → IsClifford2 a` at `n = 1`
(single qubit, object `2`).  As **literally stated about the syntax** this is **false**: the
inductive `IsClifford2` (generated by `σ_⊕, V, S` under `∘`) is *not* closed under the additive
product `⊕`, so a grade-`0` term whose head is `⊕` (other than the special `S` term) cannot be
`IsClifford2` even when its denotation is a perfectly good Clifford matrix.  The cleanest
counterexample is the global phase `ζ₃ ⊕ ζ₃`, whose denotation is `ζ₈·I` (grade `0`) but which is
not a syntactic Clifford word.  This is recorded as `Pi3.Falsification_T4_syntactic`.

The genuine, kernel-true converse is the **classification of the grade-`0` single-qubit diagonal
phases**: a conditional phase `diag(1, ζ₈ʲ)` is grade-`0` *iff* `j` is even, i.e. iff
`ζ₈ʲ ∈ {1, i, -1, -i}` — exactly the diagonal Clifford gates `{I, S, Z, S†}`.  This is
`Pi3.Headline_T4_converse_diagonal`, the sharp first-stratum statement following from the T2
`ℤ/8ℤ` table.  The full unrestricted converse (`Aut(L₃) = Clifford` up to phase, the
Kliuchnikov–Schönnenbeck/Selinger presentation) remains the conjectural frontier, exactly as the
originally flagged.
-/

set_option maxRecDepth 4000

namespace Pi3
open Z8

/-- The global phase `ζ₃ ⊕ ζ₃ : 2 → 2`, denoting `ζ₈·I`. -/
def globalZeta : Pi3 2 2 := Pi3.zet ⊞ Pi3.zet

/-- `⟦ζ₃ ⊕ ζ₃⟧ = diag(ζ₈, ζ₈) = ζ₈·I`. -/
lemma denote_globalZeta :
    denote globalZeta = Matrix.diagonal ![Q8.ofZ8 zeta, Q8.ofZ8 zeta] := by
  funext i j
  fin_cases i <;> fin_cases j <;> decide +kernel

/-- The global phase `ζ₈·I` has lattice grade `0` (it preserves `L₃`). -/
lemma grade2obj_globalZeta : grade2obj globalZeta = 0 := by
  refine le_antisymm (gradeWrt_le_of_pushesIn (k := 0) ?_) (zero_le _)
  intro v hv
  refine ⟨zeta • v, L3.smul_mem _ hv, ?_⟩
  rw [pow_zero, one_smul, denote_globalZeta]
  funext i
  fin_cases i <;>
    simp [Matrix.mulVec, Matrix.diagonal, dotProduct, coeVec,
      Pi.smul_apply, smul_eq_mul, ← Q8.ofZ8Hom_apply, ← map_mul]

/-- `ζ₃ ⊕ ζ₃` is **not** a syntactic Clifford word (its head constructor is `⊕`, which
`IsClifford2` does not produce, except for the specific term `S`). -/
lemma not_isClifford2_globalZeta : ¬ IsClifford2 globalZeta := by
  intro h
  cases h

/-- **Pi3.Falsification_T4_syntactic.** The literal syntactic converse
`grade2obj a = 0 → IsClifford2 a` is FALSE: the grade-`0` global phase `ζ₃ ⊕ ζ₃` is not a
syntactic Clifford word. -/
theorem Falsification_T4_syntactic :
    ∃ a : Pi3 2 2, grade2obj a = 0 ∧ ¬ IsClifford2 a :=
  ⟨globalZeta, grade2obj_globalZeta, not_isClifford2_globalZeta⟩

/-- **Pi3.Headline_T4_converse_diagonal.** The sharp first-stratum converse: a single-qubit
diagonal phase `diag(1, ζ₈ʲ)` is grade-`0` *iff* `j` is even, i.e. iff `ζ₈ʲ ∈ {1, i, -1, -i}` is
a diagonal Clifford phase. -/
theorem Headline_T4_converse_diagonal (j : Fin 8) :
    latGrade (diag1 (Z8.zeta ^ (j : ℕ))) = 0 ↔ (j : ℕ) % 2 = 0 := by
  rw [Headline_T2_zeta_table]
  fin_cases j <;> decide

end Pi3
