import StabilizerBW.SqrtPi.Clifford
import StabilizerBW.SqrtPi.OplusCost

/-!
# T4** — The semantic converse at one qubit is a **Verified Falsification**

The continuation asked for the *semantic* converse at `n = 1`:
> every `L₃`-preserving (integral) operator on one qubit is a phased qubit Clifford.

This is **false**, and the continuation's framework explicitly anticipates this case as a
permissible *Verified Falsification*:

> "If the semantic converse turns out to require more than `n = 1` finite enumeration (e.g. if
> `Aut(L₃)` is strictly larger than the phased Clifford group, which would itself be a Verified
> Falsification), ship that as `Pi3.Falsification_T4_semantic_n1` with the extra-automorphism
> counterexample."

The integral automorphism group `Aut(L₃)` (operators `M` with `M·L₃ = L₃` as submodules) is
**strictly larger** than the finite phased Clifford group, because it contains the
**totally-real fundamental unit** `1 + √2 ∈ ℤ[√2] ⊆ ℤ[ζ₈]`.  The diagonal operator
`diag(1, 1 + √2)` is:

* **integral** (entries in `ℤ[ζ₈]`),
* a **lattice automorphism** of `L₃` (its inverse `diag(1, √2 − 1)` is also integral and
  lattice-preserving, since `1 + √2` and `√2 − 1` are units and `(1+i) ∣ √2`), in fact of
  **lattice grade `0`** (`latGrade_Nbad`),
* but **not** a phased Clifford: its determinant `1 + √2` is not a power of `ζ₈` (it is a real
  number `> 1`, hence of infinite multiplicative order, while every phased Clifford has a root
  of unity as determinant).

So the converse is refuted at the *semantic* (matrix) level — strengthening the prior round's
merely *syntactic* falsification `Pi3.Falsification_T4_syntactic`.

The refuting invariant is the **determinant**: every phased single-qubit Clifford matrix has a
power of `ζ₈` as its determinant (`clifford2Matrix_det_isRootPow`), and `1 + √2` is not such a
power (`not_isRootPow_sqrt2plus1`).
-/

set_option maxRecDepth 4000

namespace Pi3
open Z8

/-! ### Powers of `ζ₈` -/

/-- `x` is a power of `ζ₈` (an `8`th root of unity in `ℚ[ζ₈]`). -/
def IsRootPow (x : Q8) : Prop := ∃ k : ℕ, x = (Q8.ofZ8 zeta) ^ k

lemma zeta_pow_eight : (Q8.ofZ8 zeta) ^ 8 = 1 := by decide +kernel

lemma isRootPow_one : IsRootPow 1 := ⟨0, by rw [pow_zero]⟩

lemma isRootPow_mul {x y : Q8} (hx : IsRootPow x) (hy : IsRootPow y) :
    IsRootPow (x * y) := by
  obtain ⟨j, rfl⟩ := hx
  obtain ⟨k, rfl⟩ := hy
  exact ⟨j + k, by rw [pow_add]⟩

/-- Since `ζ₈⁸ = 1`, a power of `ζ₈` is one of the eight values `ζ₈^0, …, ζ₈^7`. -/
lemma isRootPow_reduce (x : Q8) :
    IsRootPow x ↔ ∃ k : Fin 8, x = (Q8.ofZ8 zeta) ^ (k : ℕ) := by
  constructor
  · rintro ⟨k, rfl⟩
    refine ⟨⟨k % 8, Nat.mod_lt _ (by norm_num)⟩, ?_⟩
    conv_lhs => rw [← Nat.div_add_mod k 8, pow_add, pow_mul, zeta_pow_eight, one_pow, one_mul]
  · rintro ⟨k, rfl⟩; exact ⟨(k : ℕ), rfl⟩

/-! ### The phased single-qubit Clifford matrices -/

/-- A matrix is a **phased qubit Clifford** iff it is `ζ₈^k · ⟦a⟧` for some `k` and some
syntactic Clifford word `a` (generated by `X = σ_⊕`, `V`, `S` under composition).  This is the
finite single-qubit Clifford group together with the eight global phases. -/
def IsClifford2Matrix (M : Matrix (Fin 2) (Fin 2) Q8) : Prop :=
  ∃ (k : ℕ) (a : Pi3 2 2), IsClifford2 a ∧ M = (Q8.ofZ8 zeta) ^ k • denote a

/-- The determinant of a syntactic Clifford word is a power of `ζ₈`. -/
lemma clifford_det_isRootPow {a : Pi3 2 2} (h : IsClifford2 a) :
    IsRootPow (Matrix.det (denote a)) := by
  induction h with
  | idn => rw [denote_id, Matrix.det_one]; exact isRootPow_one
  | swp => exact ⟨4, by rw [denote_sigma, Matrix.det_fin_two]; decide +kernel⟩
  | vv => exact ⟨2, by rw [denote_V, Matrix.det_fin_two]; decide +kernel⟩
  | sGate => exact ⟨2, by rw [denote_sGate, Matrix.det_fin_two]; decide +kernel⟩
  | @cmp a b _ _ iha ihb =>
      rw [denote_circ, Matrix.det_mul]; exact isRootPow_mul ihb iha

/-- **Determinant invariant.** Every phased qubit Clifford matrix has a power of `ζ₈` as its
determinant. -/
lemma clifford2Matrix_det_isRootPow {M : Matrix (Fin 2) (Fin 2) Q8}
    (h : IsClifford2Matrix M) : IsRootPow (Matrix.det M) := by
  obtain ⟨k, a, ha, rfl⟩ := h
  rw [Matrix.det_smul, Fintype.card_fin]
  refine isRootPow_mul ⟨k * 2, by rw [pow_mul]⟩ (clifford_det_isRootPow ha)

/-! ### The counterexample `diag(1, 1 + √2)` -/

/-- `1 + √2 = 1 + (ζ - ζ³) ∈ ℤ[ζ₈]`. -/
def sqrt2plus1 : Z8 := ⟨1, 1, 0, -1⟩
/-- `√2 - 1 = (ζ - ζ³) - 1 ∈ ℤ[ζ₈]`, the inverse of `1 + √2`. -/
def sqrt2minus1 : Z8 := ⟨-1, 1, 0, -1⟩

/-- The integral matrix `diag(1, 1 + √2)`. -/
def Nbad : Matrix (Fin 2) (Fin 2) Z8 := diag1 sqrt2plus1
/-- The integral inverse `diag(1, √2 - 1)`. -/
def Ninv : Matrix (Fin 2) (Fin 2) Z8 := diag1 sqrt2minus1
/-- The counterexample operator `diag(1, 1 + √2)` over `ℚ[ζ₈]`. -/
def Mbad : Matrix (Fin 2) (Fin 2) Q8 := Nbad.map Q8.ofZ8
/-- The inverse `diag(1, √2 - 1)` over `ℚ[ζ₈]`. -/
def Minv : Matrix (Fin 2) (Fin 2) Q8 := Ninv.map Q8.ofZ8

/-- `M` integral: its entries lie in `ℤ[ζ₈]`. -/
def IsIntegral (M : Matrix (Fin 2) (Fin 2) Q8) : Prop :=
  ∃ N : Matrix (Fin 2) (Fin 2) Z8, M = N.map Q8.ofZ8

/-- `M` maps the lattice `L₃` into `L₃`. -/
def MapsIntoL3 (M : Matrix (Fin 2) (Fin 2) Q8) : Prop :=
  ∀ v ∈ L3, ∃ w ∈ L3, M.mulVec (coeVec v) = coeVec w

/-- `M` is an automorphism of the lattice `L₃` (`M·L₃ = L₃`): both `M` and a two-sided inverse
`N` map `L₃` into `L₃`. -/
def IsLatAut2 (M : Matrix (Fin 2) (Fin 2) Q8) : Prop :=
  MapsIntoL3 M ∧ ∃ N : Matrix (Fin 2) (Fin 2) Q8, MapsIntoL3 N ∧ M * N = 1 ∧ N * M = 1

/-- An integral diagonal `diag(1, A)` with `(1+i) ∣ (A - 1)` maps `L₃` into `L₃`. -/
lemma mapsIntoL3_integral_diag (A : Z8) (hA : onePlusI ∣ (A - 1)) :
    MapsIntoL3 ((diag1 A).map Q8.ofZ8) := by
  intro v hv
  refine ⟨(diag1 A).mulVec v, ?_, ?_⟩
  · rw [mem_L3, diag1_mulVec]
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one]
    rw [mem_L3] at hv
    have heq : v 0 + A * v 1 = (v 0 + v 1) + (A - 1) * v 1 := by ring
    rw [heq]
    exact dvd_add hv (Dvd.dvd.mul_right hA (v 1))
  · rw [map_mulVec_coeVec]

/-- `Mbad` maps `L₃` into `L₃`. -/
lemma mapsIntoL3_Mbad : MapsIntoL3 Mbad :=
  mapsIntoL3_integral_diag sqrt2plus1 (by rw [dvd_onePlusI_iff]; decide)

/-- `Minv` maps `L₃` into `L₃`. -/
lemma mapsIntoL3_Minv : MapsIntoL3 Minv :=
  mapsIntoL3_integral_diag sqrt2minus1 (by rw [dvd_onePlusI_iff]; decide)

/-- `Mbad · Minv = 1`. -/
lemma Mbad_mul_Minv : Mbad * Minv = 1 := by
  funext i j; fin_cases i <;> fin_cases j <;> decide +kernel

/-- `Minv · Mbad = 1`. -/
lemma Minv_mul_Mbad : Minv * Mbad = 1 := by
  funext i j; fin_cases i <;> fin_cases j <;> decide +kernel

/-- `Mbad` is an automorphism of `L₃` (it is `diag(1, 1+√2)` with integral inverse). -/
lemma isLatAut2_Mbad : IsLatAut2 Mbad :=
  ⟨mapsIntoL3_Mbad, Minv, mapsIntoL3_Minv, Mbad_mul_Minv, Minv_mul_Mbad⟩

/-- `det(Mbad) = 1 + √2`. -/
lemma det_Mbad : Matrix.det Mbad = Q8.ofZ8 sqrt2plus1 := by
  rw [Matrix.det_fin_two]; decide +kernel

/-- `1 + √2` is **not** a power of `ζ₈` (it is real and `> 1`, of infinite order). -/
lemma not_isRootPow_sqrt2plus1 : ¬ IsRootPow (Q8.ofZ8 sqrt2plus1) := by
  rw [isRootPow_reduce]
  rintro ⟨k, hk⟩
  fin_cases k <;> exact absurd hk (by decide +kernel)

/-- The counterexample is **not** a phased Clifford: its determinant `1 + √2` is not a power of
`ζ₈`. -/
lemma not_isClifford2Matrix_Mbad : ¬ IsClifford2Matrix Mbad := by
  intro h
  exact not_isRootPow_sqrt2plus1 (det_Mbad ▸ clifford2Matrix_det_isRootPow h)

/-- The counterexample even has lattice grade `0`: it is `diag(1, 1+√2)` with `(1+i) ∣ √2`. -/
lemma latGrade_Nbad : latGrade Nbad = 0 := by
  rw [Nbad, latGrade_diag1]; decide

/-- **Pi3.Falsification_T4_semantic_n1.** The semantic converse at one qubit is FALSE:
there is an integral lattice automorphism of `L₃` that is not a phased Clifford.  Concretely,
`diag(1, 1+√2)` (built from the totally-real fundamental unit `1+√2 ∈ ℤ[√2] ⊆ ℤ[ζ₈]`) is
integral, an automorphism of `L₃`, but not a phased qubit Clifford.  Hence `Aut(L₃)` is
**strictly larger** than the phased Clifford group. -/
theorem Falsification_T4_semantic_n1 :
    ∃ M : Matrix (Fin 2) (Fin 2) Q8,
      IsIntegral M ∧ IsLatAut2 M ∧ ¬ IsClifford2Matrix M :=
  ⟨Mbad, ⟨Nbad, rfl⟩, isLatAut2_Mbad, not_isClifford2Matrix_Mbad⟩

/-- **Pi3.Falsification_T4_grade0_semantic_n1.** Even at lattice grade `0` the semantic converse
fails: `diag(1, 1+√2)` is a grade-`0` integral lattice automorphism that is not a phased
Clifford.  This refutes "grade `0` ⟹ Clifford" at the *semantic* (matrix) level, strengthening
the prior round's syntactic `Pi3.Falsification_T4_syntactic`. -/
theorem Falsification_T4_grade0_semantic_n1 :
    latGrade Nbad = 0 ∧ IsLatAut2 Mbad ∧ ¬ IsClifford2Matrix Mbad :=
  ⟨latGrade_Nbad, isLatAut2_Mbad, not_isClifford2Matrix_Mbad⟩

end Pi3
