import StabilizerBW.SqrtPi.Pi3

/-!
# Grade `0` and the Clifford fragment at `n ≤ 2`

The single-qubit Clifford prop is generated (inside `Π₃`) by the swap `σ_⊕`, the
square-root-of-swap `V`, and the phase gate `S = id₁ ⊕ ζ₈² = diag(1, i)`.

This file proves the **soundness (forward) inclusion** of T4:
> every Clifford morphism has lattice grade `0`.

The converse inclusion (every grade-`0` morphism is Clifford) is the deep direction; as noted in
the structural strawman it reduces to the Kliuchnikov–Schönnenbeck/Selinger presentation
`Aut(BWₙ) = Clifford prop (up to phase)` and is left as the conjectural frontier.
-/

set_option maxRecDepth 4000

namespace Pi3
open Z8

/-- The phase gate `S = id₁ ⊕ (ζ₈·ζ₈) = diag(1, i) : 2 → 2`. -/
def sGate : Pi3 2 2 := Pi3.idn 1 ⊞ (Pi3.zet ⊚ Pi3.zet)

/-
`g(σ_⊕) = 0`: the swap preserves the single-qubit lattice.
-/
lemma grade2obj_swp : grade2obj Pi3.swp = 0 := by
  refine' le_antisymm ( Pi3.gradeWrt_le_of_pushesIn _ ) ( by positivity );
  intro v hv;
  refine' ⟨ fun i => v ( Equiv.swap 0 1 i ), _, _ ⟩ <;> simp_all +decide [ L3 ];
  · obtain ⟨ k, hk ⟩ := hv;
    exact ⟨ k, by simpa [ add_comm ] using hk ⟩;
  · ext i; fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct, swapMat ] ;
    · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct, swapMat ];
    · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct, swapMat ];
    · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct, swapMat ]

/-
`g(S) = 0`: the phase gate `diag(1, i)` preserves the single-qubit lattice.
-/
/-- The denotation of `S` is the diagonal matrix `diag(1, i)`. -/
lemma denote_sGate : denote sGate = Matrix.diagonal ![1, Q8.ofZ8 Z8.imag] := by
  funext i j
  fin_cases i <;> fin_cases j <;>
    simp [sGate, denote_oplus, denote_id, denote_circ, denote_zeta3, zetaMat,
      Matrix.submatrix_apply, Matrix.diagonal,
      finSumFinEquiv, Matrix.of_apply, Matrix.cons_val_zero, ← Q8.ofZ8Hom_apply, ← map_mul] <;>
    decide

lemma grade2obj_sGate : grade2obj sGate = 0 := by
  have h_sGate_denote : denote sGate = Matrix.diagonal ![1, Q8.ofZ8 Z8.imag] := denote_sGate
  refine' le_antisymm ( gradeWrt_le_of_pushesIn _ ) _;
  · intro v hv;
    refine' ⟨ fun i => if i = 0 then v 0 else imag * v 1, _, _ ⟩ <;> simp_all +decide [ mem_L3 ];
    · convert dvd_add hv ( dvd_mul_of_dvd_left ( show onePlusI ∣ imag - 1 from by
                                                  exact dvd_onePlusI_iff _ |>.2 ( by decide ) ) ( v 1 ) ) using 1 ; ring;
    · ext i; fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct ] ;
      · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct ];
      · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct ];
      · fin_cases i <;> simp +decide [ Matrix.mulVec, dotProduct ];
  · exact zero_le _

/-- The (single-qubit) Clifford fragment of `Π₃`, generated by `σ_⊕`, `V` and `S`. -/
inductive IsClifford2 : Pi3 2 2 → Prop
  | protected idn : IsClifford2 (Pi3.idn 2)
  | swp : IsClifford2 Pi3.swp
  | vv : IsClifford2 Pi3.vv
  | sGate : IsClifford2 sGate
  | cmp {a b : Pi3 2 2} : IsClifford2 a → IsClifford2 b → IsClifford2 (a ⊚ b)

/-- **T4 (Headline, forward inclusion).** Every Clifford morphism at `n ≤ 2` has lattice grade `0`.
(The converse `grade 0 ⊆ Clifford` is the deep direction, deferred to the
`Aut(BWₙ) = Clifford` presentation.) -/
theorem Headline_T4_sound {a : Pi3 2 2} (h : IsClifford2 a) : grade2obj a = 0 := by
  induction h with
  | idn =>
      show gradeWrt L3 (denote (Pi3.idn 2)) = 0
      rw [denote_id]; exact gradeWrt_id L3
  | swp => exact grade2obj_swp
  | vv => exact grade_V
  | sGate => exact grade2obj_sGate
  | @cmp a b _ _ iha ihb =>
      have hmul := grade_mul L3 a b
      simp only [grade2obj] at iha ihb ⊢
      rw [iha, ihb] at hmul
      simpa using le_antisymm hmul (zero_le _)

end Pi3