import Mathlib

/-!
# MenuBandwidthN4 / CliffordMenuN4 — T1: the `n = 4` Clifford menu and its stabilizer bound

This file lifts the three-qubit Clifford-menu construction of
``StabilizerBW.Compilation.ContextGame`` to **four qubits**: the menu is the
twelve single-qubit Pauli observables `{X_q, Y_q, Z_q : q ∈ {1,2,3,4}}`, indexed
by `Idx4 = Fin 4 × Fin 3` (`(qubit, axis)`).

The facet functional is the all-ones functional `W = Σ_{q,a} ⟨P^a_q⟩` and the key
structural fact — the n=4 analogue of `CliffordMenu.octahedron_facet_stab_bound`,
i.e. the carried hypothesis **`CliffordFacetClassicalBound4`** of the structural strawman —
is *proved* here directly via the octahedron-norm argument lifted to four qubits:

* `CliffordMenuN4.octahedron_facet_stab_bound4` — every four-qubit stabilizer
  state satisfies `W ≤ 4`.  Thus `classicalBound = 4` is a genuine valid bound,
  matching the per-qubit ℓ¹ Bloch bound, and is the exact maximum (attained by the
  product of fixed-axis Pauli eigenstates).

The development is entirely over `ℝ` (the convex-geometry layer), mirroring
Layer 13: a profile `e : Idx4 → ℝ` records the menu expectation values
`⟨M_i⟩ ∈ [-1,1]`, and the stabilizer side uses the (proved) fact that the
realisable profiles form the convex hull of the deterministic octahedron-vertex
profiles.
-/

open scoped BigOperators

namespace CliffordMenuN4

/-! ## §1  Menu facet functionals and the stabilizer polytope (generic) -/

section General

variable {ι : Type*} [Fintype ι]

/-- The menu **facet functional** `∑ᵢ αᵢ ⟨Mᵢ⟩` evaluated on an expectation
    profile `e`. -/
def facetValue (α : ι → ℝ) (e : ι → ℝ) : ℝ := ∑ i, α i * e i

/-- A profile `e` lies in the **stabilizer polytope** generated by a finite
    vertex set `S` if it is a convex combination of the vertices. -/
def InPolytope (S : Finset (ι → ℝ)) (e : ι → ℝ) : Prop :=
  ∃ w : (ι → ℝ) → ℝ,
    (∀ p, 0 ≤ w p) ∧ (∑ p ∈ S, w p = 1) ∧ (∀ i, e i = ∑ p ∈ S, w p * p i)

/-- **Convexity bound:** if the facet functional is `≤ C` on every vertex, it is
    `≤ C` on the whole polytope. -/
theorem facetValue_le_of_polytope (α : ι → ℝ) (C : ℝ) (S : Finset (ι → ℝ))
    (hS : ∀ p ∈ S, facetValue α p ≤ C) {e : ι → ℝ} (he : InPolytope S e) :
    facetValue α e ≤ C := by
  obtain ⟨w, hw0, hw1, hwe⟩ := he
  have h_subst : facetValue α e = ∑ p ∈ S, w p * facetValue α p := by
    simp only [facetValue, hwe, Finset.mul_sum]
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl (fun p _ => Finset.sum_congr rfl (fun i _ => by ring))
  rw [h_subst]
  calc ∑ p ∈ S, w p * facetValue α p
      ≤ ∑ p ∈ S, w p * C :=
        Finset.sum_le_sum (fun p hp => mul_le_mul_of_nonneg_left (hS p hp) (hw0 p))
    _ = C := by rw [← Finset.sum_mul, hw1, one_mul]

end General

/-! ## §2  The concrete 4-qubit Clifford-menu game

Observables are indexed by `(q, a) : Fin 4 × Fin 3`: `q` the qubit, `a ∈ {0,1,2}`
the Pauli axis `X, Y, Z`.  Twelve single-qubit Pauli observables, all-ones facet
functional `W = Σ_{q,a} ⟨P^a_q⟩`, threshold `C = 4`. -/

/-- Observable index: `(qubit, axis)`, twelve in total. -/
abbrev Idx4 := Fin 4 × Fin 3

/-- The all-ones facet coefficients `αₖ = 1`. -/
def coeffOne : Idx4 → ℝ := fun _ => 1

/-- The facet threshold `C = 4` (the per-qubit ℓ¹ Bloch bound summed over four
    qubits; the maximum of `W` over the 4-qubit stabilizer polytope). -/
def menuC : ℝ := 4

/-- A single-qubit octahedron vertex: axis `a` with sign `s`: `±1` on the fixed
    axis, `0` on the two anticommuting axes. -/
noncomputable def octVertex (a : Fin 3) (s : Bool) : Fin 3 → ℝ :=
  fun b => if b = a then (if s then (1 : ℝ) else -1) else 0

/-- A 4-qubit stabilizer vertex profile: a per-qubit octahedron vertex. -/
noncomputable def menuVertex (c : Fin 4 → Fin 3 × Bool) : Idx4 → ℝ :=
  fun qa => octVertex (c qa.1).1 (c qa.1).2 qa.2

/-- The vertex set of the 4-qubit stabilizer polytope (the `6⁴ = 1296`
    deterministic profiles). -/
noncomputable def menuVertices : Finset (Idx4 → ℝ) :=
  Finset.image menuVertex Finset.univ

/-! ### PL_n forcing -/

theorem octVertex_abs_le_one (a : Fin 3) (s : Bool) (b : Fin 3) :
    |octVertex a s b| ≤ 1 := by
  unfold octVertex; split_ifs <;> norm_num

/-- The single-qubit facet value `⟨X⟩+⟨Y⟩+⟨Z⟩` of a forced (octahedron-vertex)
    profile is `±1`, hence `≤ 1`. -/
theorem octVertex_sum_le_one (a : Fin 3) (s : Bool) :
    ∑ b, octVertex a s b ≤ 1 := by
  unfold octVertex; split_ifs <;> norm_num

/-! ### Part (a): the stabilizer facet bound -/

/-- The facet value of a single 4-qubit stabilizer vertex is `≤ 4`. -/
theorem menuVertex_facet_le (c : Fin 4 → Fin 3 × Bool) :
    facetValue coeffOne (menuVertex c) ≤ menuC := by
  convert Finset.sum_le_sum fun q _ => octVertex_sum_le_one (c q |>.1) (c q |>.2) using 1
  · convert Fintype.sum_prod_type
      fun i : Fin 4 × Fin 3 => octVertex (c i.1 |>.1) (c i.1 |>.2) i.2 using 1
    exact Finset.sum_congr rfl fun _ _ => by unfold coeffOne menuVertex; aesop
  · norm_num [menuC]

/-- **T1 / `CliffordFacetClassicalBound4` (proved):** every profile in the
    4-qubit stabilizer polytope satisfies the menu facet inequality `W ≤ 4`. -/
theorem octahedron_facet_stab_bound4 {e : Idx4 → ℝ}
    (he : InPolytope menuVertices e) :
    facetValue coeffOne e ≤ menuC := by
  refine facetValue_le_of_polytope coeffOne menuC menuVertices ?_ he
  intro p hp
  rw [menuVertices, Finset.mem_image] at hp
  obtain ⟨c, _, rfl⟩ := hp
  exact menuVertex_facet_le c

/-! ### The threshold is attained: `C = 4` is the exact maximum -/

/-- The all-`+Z` stabilizer vertex: every qubit fixed to the `Z = +1` eigenstate. -/
noncomputable def allZPlus : Idx4 → ℝ := menuVertex (fun _ => (2, true))

/-- The all-`+Z` vertex attains `W = 4`, so the bound `C = 4` is tight. -/
theorem allZPlus_facet_value : facetValue coeffOne allZPlus = menuC := by
  unfold facetValue coeffOne allZPlus menuVertex octVertex menuC
  simp only [one_mul]
  rw [Fintype.sum_prod_type]
  norm_num [Fin.sum_univ_succ]

end CliffordMenuN4
