import RequestProject.Roots.Grades

/-!
# The level-3 Barnes–Wall lattice `BW₂ = L₄` and the n=2 diagonal grades (Priority 3)

This file builds the two-qubit (4-dimensional) Barnes–Wall lattice over `R = ℤ[ζ₈]`
and computes the λ-adic grades of the standard `n = 2` diagonal gates, completing the
`n = 2` instances of the **diagonal character formula** (Priority 3):

* `g(CZ) = 0` (`CZ` is Clifford),
* `g(CS) = 2`,
* `g(T ⊗ T) = 2`,
* `g(diag(1,1,1,ζ₈)) = 3` (controlled-`T`, the "delta" character).

`BW₂` is the symmetric level-3 lattice (basis order `00,01,10,11`):

```
L₄ = { (x₀,x₁,x₂,x₃) : (1+i) ∣ x₀+x₁, (1+i) ∣ x₂+x₃,
 (1+i) ∣ x₀-x₂, (1+i) ∣ x₁-x₃,
 (1+i)² ∣ x₀+x₁-x₂-x₃ }
```

i.e. the iterated `(1+i)`-divisibility condition: each half is in `L₃` and the two
halves agree modulo `(1+i)·L₃`. It is an `R`-submodule generated by
`G₁=(1,-1,1,-1)`, `G₂=(0,1+i,0,1+i)`, `G₃=(0,0,-(1+i),1+i)`, `G₄=(0,0,0,-(1+i)²)`.

The grade of a diagonal operator `D` is `g(D) = min k with λ^k·D·L₄ ⊆ L₄`; we package
it as `gradeLE2 D k := MapsToL2 (scale (λ^k) D)`, mirroring the single-qubit
development in `Roots.Grades`.
-/

namespace Roots
open Z8

/-- A vector in `R⁴`, the two-qubit column space (basis order `00,01,10,11`). -/
structure Vec4 where
 c0 : Z8
 c1 : Z8
 c2 : Z8
 c3 : Z8
deriving DecidableEq, Repr

namespace Vec4
@[ext] theorem ext' {v w : Vec4} (h0 : v.c0 = w.c0) (h1 : v.c1 = w.c1)
 (h2 : v.c2 = w.c2) (h3 : v.c3 = w.c3) : v = w := by
 cases v; cases w; simp_all
end Vec4

/-! ## Membership in `BW₂ = L₄` -/

/-- Membership in the level-3 Barnes–Wall lattice `BW₂ = L₄`. -/
def inL2 (v : Vec4) : Prop :=
 Z8.oneI ∣ (v.c0 + v.c1) ∧ Z8.oneI ∣ (v.c2 + v.c3) ∧
 Z8.oneI ∣ (v.c0 - v.c2) ∧ Z8.oneI ∣ (v.c1 - v.c3) ∧
 (Z8.oneI * Z8.oneI) ∣ (v.c0 + v.c1 - v.c2 - v.c3)

/-! ## Decidable parity criterion -/

/-
`2 ∣ z` iff every coordinate of `z` is even.
-/
theorem two_dvd_iff_even2 (z : Z8) : (2 : Z8) ∣ z ↔ Even2 z := by
 have h2 : (2 : Z8) = ⟨2, 0, 0, 0⟩ := by decide
 unfold Even2
 constructor
 · rintro ⟨w, rfl⟩
 refine ⟨⟨w.a, ?_⟩, ⟨w.b, ?_⟩, ⟨w.c, ?_⟩, ⟨w.d, ?_⟩⟩ <;>
 rw [h2] <;> simp [Z8.mul_a, Z8.mul_b, Z8.mul_c, Z8.mul_d]
 · rintro ⟨⟨pa, ha⟩, ⟨pb, hb⟩, ⟨pc, hc⟩, ⟨pd, hd⟩⟩
 exact ⟨⟨pa, pb, pc, pd⟩, by apply Z8.ext' <;> rw [h2] <;>
 simp [Z8.mul_a, Z8.mul_b, Z8.mul_c, Z8.mul_d] <;> omega⟩

/-
`(1+i)² ∣ z` iff every coordinate of `z` is even (since `(1+i)² = 2i ∼ 2`).
-/
theorem oneISq_dvd_iff (z : Z8) : (Z8.oneI * Z8.oneI) ∣ z ↔ Even2 z := by
 rw [oneI_sq, ← two_dvd_iff_even2]
 constructor
 · rintro ⟨w, rfl⟩; exact ⟨Z8.iu * w, by ring⟩
 · rintro ⟨w, rfl⟩
 refine ⟨-Z8.iu * w, ?_⟩
 have h : Z8.iu * (-Z8.iu) = 1 := by decide
 linear_combination -(2 * w) * h

/-- Decidable parity criterion for `inL2`. -/
def inL2crit (v : Vec4) : Prop :=
 Z8.dvdOneI (v.c0 + v.c1) ∧ Z8.dvdOneI (v.c2 + v.c3) ∧
 Z8.dvdOneI (v.c0 - v.c2) ∧ Z8.dvdOneI (v.c1 - v.c3) ∧
 Even2 (v.c0 + v.c1 - v.c2 - v.c3)

instance (v : Vec4) : Decidable (inL2crit v) := by unfold inL2crit Even2; infer_instance

theorem inL2_iff (v : Vec4) : inL2 v ↔ inL2crit v := by
 unfold inL2 inL2crit
 rw [← dvdOneI_iff, ← dvdOneI_iff, ← dvdOneI_iff, ← dvdOneI_iff, oneISq_dvd_iff]

instance : DecidablePred inL2 := fun v => decidable_of_iff _ (inL2_iff v).symm

/-! ## `R`-module structure -/

/-- Scalar action of `R` on `R⁴`. -/
def vsmul4 (r : Z8) (v : Vec4) : Vec4 := ⟨r * v.c0, r * v.c1, r * v.c2, r * v.c3⟩

/-- Vector addition on `R⁴`. -/
def vadd4 (v w : Vec4) : Vec4 := ⟨v.c0 + w.c0, v.c1 + w.c1, v.c2 + w.c2, v.c3 + w.c3⟩

@[simp] theorem vsmul4_c0 (r v) : (vsmul4 r v).c0 = r * v.c0 := rfl
@[simp] theorem vsmul4_c1 (r v) : (vsmul4 r v).c1 = r * v.c1 := rfl
@[simp] theorem vsmul4_c2 (r v) : (vsmul4 r v).c2 = r * v.c2 := rfl
@[simp] theorem vsmul4_c3 (r v) : (vsmul4 r v).c3 = r * v.c3 := rfl
@[simp] theorem vadd4_c0 (v w) : (vadd4 v w).c0 = v.c0 + w.c0 := rfl
@[simp] theorem vadd4_c1 (v w) : (vadd4 v w).c1 = v.c1 + w.c1 := rfl
@[simp] theorem vadd4_c2 (v w) : (vadd4 v w).c2 = v.c2 + w.c2 := rfl
@[simp] theorem vadd4_c3 (v w) : (vadd4 v w).c3 = v.c3 + w.c3 := rfl

theorem inL2_add {v w : Vec4} (hv : inL2 v) (hw : inL2 w) : inL2 (vadd4 v w) := by
 obtain ⟨a1,a2,a3,a4,a5⟩ := hv
 obtain ⟨b1,b2,b3,b4,b5⟩ := hw
 refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> simp only [vadd4]
 · rw [show v.c0 + w.c0 + (v.c1 + w.c1) = (v.c0 + v.c1) + (w.c0 + w.c1) by ring]
 exact dvd_add a1 b1
 · rw [show v.c2 + w.c2 + (v.c3 + w.c3) = (v.c2 + v.c3) + (w.c2 + w.c3) by ring]
 exact dvd_add a2 b2
 · rw [show v.c0 + w.c0 - (v.c2 + w.c2) = (v.c0 - v.c2) + (w.c0 - w.c2) by ring]
 exact dvd_add a3 b3
 · rw [show v.c1 + w.c1 - (v.c3 + w.c3) = (v.c1 - v.c3) + (w.c1 - w.c3) by ring]
 exact dvd_add a4 b4
 · rw [show v.c0 + w.c0 + (v.c1 + w.c1) - (v.c2 + w.c2) - (v.c3 + w.c3)
 = (v.c0 + v.c1 - v.c2 - v.c3) + (w.c0 + w.c1 - w.c2 - w.c3) by ring]
 exact dvd_add a5 b5

theorem inL2_vsmul (r : Z8) {v : Vec4} (hv : inL2 v) : inL2 (vsmul4 r v) := by
 obtain ⟨a1,a2,a3,a4,a5⟩ := hv
 refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> simp only [vsmul4]
 · rw [show r * v.c0 + r * v.c1 = r * (v.c0 + v.c1) by ring]; exact Dvd.dvd.mul_left a1 r
 · rw [show r * v.c2 + r * v.c3 = r * (v.c2 + v.c3) by ring]; exact Dvd.dvd.mul_left a2 r
 · rw [show r * v.c0 - r * v.c2 = r * (v.c0 - v.c2) by ring]; exact Dvd.dvd.mul_left a3 r
 · rw [show r * v.c1 - r * v.c3 = r * (v.c1 - v.c3) by ring]; exact Dvd.dvd.mul_left a4 r
 · rw [show r * v.c0 + r * v.c1 - r * v.c2 - r * v.c3
 = r * (v.c0 + v.c1 - v.c2 - v.c3) by ring]
 exact Dvd.dvd.mul_left a5 r

/-! ## Generators -/

/-- `G₁ = (1, -1, 1, -1)`. -/
def G1 : Vec4 := ⟨1, -1, 1, -1⟩
/-- `G₂ = (0, 1+i, 0, 1+i)`. -/
def G2 : Vec4 := ⟨0, Z8.oneI, 0, Z8.oneI⟩
/-- `G₃ = (0, 0, -(1+i), 1+i)`. -/
def G3 : Vec4 := ⟨0, 0, -Z8.oneI, Z8.oneI⟩
/-- `G₄ = (0, 0, 0, -(1+i)²)`. -/
def G4 : Vec4 := ⟨0, 0, 0, -(Z8.oneI * Z8.oneI)⟩

theorem inL2_G1 : inL2 G1 := by decide
theorem inL2_G2 : inL2 G2 := by decide
theorem inL2_G3 : inL2 G3 := by decide
theorem inL2_G4 : inL2 G4 := by decide

/-
Every `L₄` vector is an `R`-combination of `G₁, G₂, G₃, G₄`.
-/
theorem inL2_decompose {v : Vec4} (hv : inL2 v) :
 ∃ a al be : Z8,
 v = vadd4 (vsmul4 v.c0 G1)
 (vadd4 (vsmul4 a G2) (vadd4 (vsmul4 al G3) (vsmul4 be G4))) := by
 obtain ⟨a, ha⟩ := hv.1
 obtain ⟨al, hal⟩ := hv.2.2.1
 obtain ⟨be, hbe⟩ := hv.2.2.2.2
 refine ⟨a, al, be, ?_⟩
 apply Vec4.ext' <;> simp only [vadd4, vsmul4, G1, G2, G3, G4]
 · ring
 · linear_combination ha
 · linear_combination -hal
 · linear_combination ha + hal - hbe

/-! ## Diagonal operators and their grade -/

/-- A diagonal operator on `R⁴`, given by its four diagonal entries. -/
abbrev Diag4 := Vec4

/-- The action of a diagonal operator (componentwise multiplication). -/
def dapply (D v : Vec4) : Vec4 := ⟨D.c0 * v.c0, D.c1 * v.c1, D.c2 * v.c2, D.c3 * v.c3⟩

/-- Scaling a diagonal operator by a ring element. -/
def scale4 (r : Z8) (D : Vec4) : Vec4 := ⟨r * D.c0, r * D.c1, r * D.c2, r * D.c3⟩

@[simp] theorem dapply_c0 (D v) : (dapply D v).c0 = D.c0 * v.c0 := rfl
@[simp] theorem dapply_c1 (D v) : (dapply D v).c1 = D.c1 * v.c1 := rfl
@[simp] theorem dapply_c2 (D v) : (dapply D v).c2 = D.c2 * v.c2 := rfl
@[simp] theorem dapply_c3 (D v) : (dapply D v).c3 = D.c3 * v.c3 := rfl

theorem dapply_add (D v w : Vec4) :
 dapply D (vadd4 v w) = vadd4 (dapply D v) (dapply D w) := by
 apply Vec4.ext' <;> simp [dapply, vadd4] <;> ring

theorem dapply_vsmul (D : Vec4) (r : Z8) (v : Vec4) :
 dapply D (vsmul4 r v) = vsmul4 r (dapply D v) := by
 apply Vec4.ext' <;> simp [dapply, vsmul4] <;> ring

theorem dapply_scale4 (r : Z8) (D v : Vec4) :
 dapply (scale4 r D) v = vsmul4 r (dapply D v) := by
 apply Vec4.ext' <;> simp [dapply, scale4, vsmul4] <;> ring

/-- A diagonal operator maps `L₄` into `L₄`. -/
def MapsToL2 (D : Vec4) : Prop := ∀ v, inL2 v → inL2 (dapply D v)

/-- **Reduction lemma.** A diagonal operator preserves `L₄` iff it preserves the four
generators. -/
theorem mapsToL2_of_gens (D : Vec4)
 (h1 : inL2 (dapply D G1)) (h2 : inL2 (dapply D G2))
 (h3 : inL2 (dapply D G3)) (h4 : inL2 (dapply D G4)) : MapsToL2 D := by
 intro v hv
 obtain ⟨a, al, be, hdec⟩ := inL2_decompose hv
 rw [hdec, dapply_add, dapply_vsmul, dapply_add, dapply_vsmul, dapply_add,
 dapply_vsmul, dapply_vsmul]
 exact inL2_add (inL2_vsmul _ h1)
 (inL2_add (inL2_vsmul _ h2) (inL2_add (inL2_vsmul _ h3) (inL2_vsmul _ h4)))

/-- `gradeLE2 D k`: the operator `λ^k · D` maps `L₄` into `L₄`. -/
def gradeLE2 (D : Vec4) (k : ℕ) : Prop := MapsToL2 (scale4 (Z8.lam ^ k) D)

theorem mapsToL2_scale (r : Z8) {D : Vec4} (h : MapsToL2 D) : MapsToL2 (scale4 r D) := by
 intro v hv
 rw [dapply_scale4]
 exact inL2_vsmul r (h v hv)

/-- `gradeLE2` is upward closed. -/
theorem gradeLE2_succ {D : Vec4} {k : ℕ} (h : gradeLE2 D k) : gradeLE2 D (k + 1) := by
 unfold gradeLE2 at *
 have hsc : scale4 (Z8.lam ^ (k + 1)) D = scale4 Z8.lam (scale4 (Z8.lam ^ k) D) := by
 apply Vec4.ext' <;> simp [scale4] <;> ring
 rw [hsc]
 exact mapsToL2_scale Z8.lam h

/-- `gradeLE2` is monotone in `k`. -/
theorem gradeLE2_of_le {D : Vec4} {a b : ℕ} (h : gradeLE2 D a) (hab : a ≤ b) :
 gradeLE2 D b := by
 induction hab with
 | refl => exact h
 | step _ ih => exact gradeLE2_succ ih

/-- `2 ∣ λ⁴`, so `λ⁴` lands every coordinate in `2R`. -/
theorem two_dvd_lam_pow_four : (2 : Z8) ∣ Z8.lam ^ 4 := by
 refine ⟨Z8.iu * Z8.uu ^ 2, ?_⟩; decide

/-
Every diagonal operator has grade `≤ 4` (since `λ⁴ ∼ 2`).
-/
theorem gradeLE2_top (D : Vec4) : gradeLE2 D 4 := by
 intro v hv;
 -- Write `w` for `dapply D v`; goal is `inL2 (vsmul4 (Z8.lam^4) w)`.
 set w : Vec4 := dapply D v
 have hw : inL2 (vsmul4 (Z8.lam ^ 4) w) := by
 -- Since `Z8.oneI ∣ Z8.lam^4` and `(Z8.oneI * Z8.oneI) ∣ Z8.lam^4`, we can show `inL2 (vsmul4 (Z8.lam^4) w)` using `inL2_vsmul`.
 have h_div : Z8.oneI ∣ Z8.lam ^ 4 ∧ (Z8.oneI * Z8.oneI) ∣ Z8.lam ^ 4 := by
 exact ⟨ dvd_trans ⟨ ⟨ 1, 0, -1, 0 ⟩, by decide ⟩ two_dvd_lam_pow_four, dvd_trans ⟨ -Z8.iu, by decide ⟩ two_dvd_lam_pow_four ⟩;
 refine ⟨ ?_, ?_, ?_, ?_, ?_ ⟩ <;> simp_all +decide [ vsmul4 ];
 · exact dvd_add ( dvd_mul_of_dvd_left h_div.1 _ ) ( dvd_mul_of_dvd_left h_div.1 _ );
 · exact dvd_add ( dvd_mul_of_dvd_left h_div.1 _ ) ( dvd_mul_of_dvd_left h_div.1 _ );
 · exact dvd_sub ( dvd_mul_of_dvd_left h_div.1 _ ) ( dvd_mul_of_dvd_left h_div.1 _ );
 · exact dvd_sub ( dvd_mul_of_dvd_left h_div.1 _ ) ( dvd_mul_of_dvd_left h_div.1 _ );
 · convert Dvd.dvd.mul_right h_div.2 ( w.c0 + w.c1 - w.c2 - w.c3 ) using 1 ; ring;
 rwa [ dapply_scale4 ]

theorem gradeLE2_nonempty (D : Vec4) : ∃ k, gradeLE2 D k := ⟨4, gradeLE2_top D⟩

/-- The grade `g(D) = min k with λ^k·D·L₄ ⊆ L₄`. -/
noncomputable def grade2 (D : Vec4) : ℕ := sInf {k | gradeLE2 D k}

theorem gradeLE2_grade (D : Vec4) : gradeLE2 D (grade2 D) :=
 Nat.sInf_mem (gradeLE2_nonempty D)

theorem grade2_le {D : Vec4} {k : ℕ} (h : gradeLE2 D k) : grade2 D ≤ k :=
 Nat.sInf_le h

theorem grade2_eq_zero {D : Vec4} (h0 : gradeLE2 D 0) : grade2 D = 0 :=
 Nat.le_zero.mp (Nat.sInf_le h0)

/-- If `λ^m·D` preserves `L₄` but `λ^{m-1}·D` does not, the grade is exactly `m`. -/
theorem grade2_eq_of {D : Vec4} {m : ℕ} (hm : gradeLE2 D m)
 (hpred : ¬ gradeLE2 D (m - 1)) : grade2 D = m := by
 have hmem : grade2 D ∈ {k | gradeLE2 D k} := Nat.sInf_mem (gradeLE2_nonempty D)
 have hle : grade2 D ≤ m := Nat.sInf_le hm
 rcases Nat.lt_or_ge (grade2 D) m with h | h
 · exact absurd (gradeLE2_of_le hmem (by omega : grade2 D ≤ m - 1)) hpred
 · omega

/-! ## The witness for the lower bounds: `W = (i, -i, i, -i) ∈ L₄` -/

/-- `W = (i, -i, i, -i)` lies in `L₄`. -/
def W : Vec4 := ⟨Z8.iu, -Z8.iu, Z8.iu, -Z8.iu⟩

theorem inL2_W : inL2 W := by decide

/-! ## Priority 3 — the `n = 2` diagonal grades -/

/-- `CZ = diag(1,1,1,-1)`. -/
def CZ : Vec4 := ⟨1, 1, 1, -1⟩
/-- `CS = diag(1,1,1,i)`. -/
def CS : Vec4 := ⟨1, 1, 1, Z8.iu⟩
/-- `T ⊗ T = diag(1, ζ, ζ, ζ²)`. -/
def TT : Vec4 := ⟨1, Z8.zeta, Z8.zeta, Z8.zeta ^ 2⟩
/-- `cT = diag(1,1,1,ζ)` (controlled-`T`). -/
def cT : Vec4 := ⟨1, 1, 1, Z8.zeta⟩
/-- `T ⊗ I = diag(1, 1, ζ, ζ)`. -/
def TI : Vec4 := ⟨1, 1, Z8.zeta, Z8.zeta⟩

/-- **Priority 3: `g(CZ) = 0`** — `CZ` is Clifford. -/
theorem grade2_CZ : grade2 CZ = 0 := by
 apply grade2_eq_zero
 unfold gradeLE2
 simp only [pow_zero]
 apply mapsToL2_of_gens <;> decide

/-- **Priority 3: `g(T ⊗ I) = 1`** (grade adds under tensoring: `g(T⊗I)=g(T)=1`). -/
theorem grade2_TI : grade2 TI = 1 := by
 apply grade2_eq_of (m := 1)
 · unfold gradeLE2; apply mapsToL2_of_gens <;> decide
 · intro h
 have := h W inL2_W
 revert this; decide

/-- **Priority 3: `g(CS) = 2`.** -/
theorem grade2_CS : grade2 CS = 2 := by
 apply grade2_eq_of (m := 2)
 · unfold gradeLE2; apply mapsToL2_of_gens <;> decide
 · intro h
 have := h W inL2_W
 revert this; decide

/-- **Priority 3: `g(T ⊗ T) = 2`.** -/
theorem grade2_TT : grade2 TT = 2 := by
 apply grade2_eq_of (m := 2)
 · unfold gradeLE2; apply mapsToL2_of_gens <;> decide
 · intro h
 have := h W inL2_W
 revert this; decide

/-- **Priority 3: `g(diag(1,1,1,ζ₈)) = 3`** (controlled-`T`, the delta character). -/
theorem grade2_cT : grade2 cT = 3 := by
 apply grade2_eq_of (m := 3)
 · unfold gradeLE2; apply mapsToL2_of_gens <;> decide
 · intro h
 have := h W inL2_W
 revert this; decide

end Roots