import StabilizerBW.Roots.AutL3Unitary

/-!
# Companion: the `ℤ[1/√2, ζ₈]` denominator restores Hadamard (order `8 → 24`)

This file is the publishable companion to `StabilizerBW.Roots.AutL3Unitary`.
There we proved that the unitary `2×2` lattice automorphisms of `L₃` that are
**integral over `ℤ[ζ₈]`** form the *monomial* Clifford group — projective
order `8`, special-unitary order `16` — because the Hadamard gate
`H = (1/√2)·[[1,1],[1,-1]]` has entries `±1/√2 ∉ ℤ[ζ₈]` and is therefore
excluded.

Here we make the **denominator change** explicit: over the localisation
`ℤ[1/√2, ζ₈] = ℤ[ζ₈][1/2]`, the element `1/√2` exists, so the Hadamard gate is
in the ring and the projective single-qubit Clifford group is restored to its
full order `24`.

The narrative, stated as theorems:

* **Order `8 → 24`.**  The single-qubit projective Clifford group, realised by
  its faithful action on the six stabiliser states (the `±X, ±Y, ±Z`
  eigenstates, encoded as `Fin 6` / length-`6` image vectors), has order `24`
  (`clifford24_card`, `clifford24_generated`).  Its *monomial* subgroup — the
  `ℤ[ζ₈]`-integral part generated by the phase gate `S` and Pauli `X` — has
  order `8` (`clifford8_card`, `clifford8_generated`).  The inclusion is strict,
  the missing element being the Hadamard action `permH`
  (`permH_mem_24`, `permH_not_mem_8`).

* **Hadamard is integral over `ℤ[1/√2, ζ₈]` but not over `ℤ[ζ₈]`.**  The scalar
  `1/√2` is not in `ℤ[ζ₈]` (`sqrt2_not_unit` — `√2` is not a unit there), so `H`
  cannot be written over `ℤ[ζ₈]`; but in the dyadic localisation it is a genuine
  unitary (`hadamard_unitary_halfSqrt2`).

This is *not* the original "discharge K–S over `ℤ[ζ₈]`" — that count
is `16`, see the companion file.  It is the standard single-qubit Clifford count
`24`, recovered exactly when the ring is enlarged to admit `1/√2`.  Pairing the
two files gives the publishable narrative: **a one-line denominator change
toggles the projective order from `8` to `24`, and surfaces the Hadamard gate as
the unique non-monomial Clifford generator.**

## On the model of "order 24"

The projective single-qubit Clifford group acts faithfully on the `6` stabiliser
states (the octahedron of Pauli eigenstates) as the rotation group `≅ S₄` of
order `24` (cf. `lean-context/BarnesWall.lean` in the abstract).  We use
exactly that faithful permutation action as the model of the group, encoding a
permutation of the six states by its image vector `[f 0, …, f 5] : List ℕ`.
Composition is `pcomp`; all group facts are kernel computations (`decide`, no
`native_decide`).
-/

set_option maxRecDepth 8000
set_option maxHeartbeats 4000000

namespace AutL3HalfSqrt2

/-! ## Part A — the projective Clifford group as permutations of the 6 states -/

/-- A permutation of the six stabiliser states, encoded as its image vector
`[f 0, f 1, …, f 5]`. -/
abbrev Perm6 := List Nat

/-- Application of an encoded permutation. -/
def app (v : Perm6) (i : Nat) : Nat := v.getD i 0

/-- Composition of encoded permutations `(a ∘ b)`. -/
def pcomp (a b : Perm6) : Perm6 := (List.range 6).map (fun i => app a (app b i))

/-- Identity permutation. -/
def pid : Perm6 := [0, 1, 2, 3, 4, 5]

/-- The phase gate `S` action on the six states. -/
def permS : Perm6 := [0, 1, 4, 5, 3, 2]
/-- The Hadamard gate `H` action on the six states (the non-monomial generator). -/
def permH : Perm6 := [2, 3, 0, 1, 5, 4]
/-- The Pauli `X` action on the six states. -/
def permX : Perm6 := [1, 0, 2, 3, 5, 4]

/-- One closure step: add all pairwise composites not already present. -/
def insv (acc : List Perm6) (x : Perm6) : List Perm6 :=
  if acc.contains x then acc else x :: acc

/-- Iterate pairwise composition once over a list, accumulating new elements. -/
def step (l : List Perm6) : List Perm6 :=
  (l.flatMap (fun a => l.map (fun b => pcomp a b))).foldl insv l

/-- Two lists describe the same set. -/
def sameSet (a b : List Perm6) : Bool := a.all (b.contains ·) && b.all (a.contains ·)

/-- The `24` elements of the projective single-qubit Clifford group, as image
vectors (the closure of `{1, S, H}` under composition). -/
def cliffList24 : List Perm6 :=
  [[0,1,2,3,4,5],[0,1,4,5,3,2],[2,3,0,1,5,4],[0,1,3,2,5,4],[4,5,0,1,2,3],[2,3,5,4,1,0],
   [0,1,5,4,2,3],[3,2,0,1,4,5],[4,5,2,3,1,0],[2,3,1,0,4,5],[5,4,2,3,0,1],[5,4,0,1,3,2],
   [3,2,4,5,1,0],[4,5,1,0,3,2],[2,3,4,5,0,1],[1,0,2,3,5,4],[5,4,3,2,1,0],[3,2,1,0,5,4],
   [4,5,3,2,0,1],[1,0,4,5,2,3],[1,0,5,4,3,2],[5,4,1,0,2,3],[3,2,5,4,0,1],[1,0,3,2,4,5]]

/-- The `8` elements of the monomial (`ℤ[ζ₈]`-integral) Clifford subgroup, as
image vectors (the closure of `{1, S, X}` under composition). -/
def cliffList8 : List Perm6 :=
  [[0,1,2,3,4,5],[0,1,4,5,3,2],[1,0,2,3,5,4],[0,1,3,2,5,4],
   [1,0,4,5,2,3],[1,0,5,4,3,2],[0,1,5,4,2,3],[1,0,3,2,4,5]]

/-- The Clifford group as a `Finset`. -/
def cliff24 : Finset Perm6 := cliffList24.toFinset
/-- The monomial Clifford subgroup as a `Finset`. -/
def cliff8 : Finset Perm6 := cliffList8.toFinset

/-! ### Cardinalities -/

/-- The projective single-qubit Clifford group has order `24`. -/
theorem clifford24_card : cliff24.card = 24 := by decide

/-- The monomial (`ℤ[ζ₈]`-integral) Clifford subgroup has order `8`. -/
theorem clifford8_card : cliff8.card = 8 := by decide

/-! ### Generation -/

/-- `cliffList24` is exactly the closure of `{1, S, H}` under composition:
the single-qubit Clifford group is generated by the phase gate and Hadamard. -/
theorem clifford24_generated :
    sameSet (step^[6] [pid, permS, permH]) cliffList24 = true := by decide

/-- `cliffList8` is exactly the closure of `{1, S, X}` under composition:
the monomial Clifford subgroup is generated by the phase gate and Pauli `X`. -/
theorem clifford8_generated :
    sameSet (step^[6] [pid, permS, permX]) cliffList8 = true := by decide

/-! ### Closure under composition (subgroup property) -/

/-- `cliffList24` is closed under composition. -/
theorem clifford24_closedB :
    cliffList24.all (fun a => cliffList24.all (fun b => cliffList24.contains (pcomp a b)))
      = true := by decide

/-- `cliffList8` is closed under composition. -/
theorem clifford8_closedB :
    cliffList8.all (fun a => cliffList8.all (fun b => cliffList8.contains (pcomp a b)))
      = true := by decide

/-! ### The `8 → 24` toggle, witnessed by Hadamard -/

/-- The generators `1, S, H` are in the order-`24` group. -/
theorem gens24_mem : pid ∈ cliff24 ∧ permS ∈ cliff24 ∧ permH ∈ cliff24 := by decide

/-- The generators `1, S, X` are in the order-`8` monomial group. -/
theorem gens8_mem : pid ∈ cliff8 ∧ permS ∈ cliff8 ∧ permX ∈ cliff8 := by decide

/-- The monomial subgroup is contained in the full Clifford group. -/
theorem clifford8_subset_24 : cliff8 ⊆ cliff24 := by decide

/-- The Hadamard action lies in the full Clifford group. -/
theorem permH_mem_24 : permH ∈ cliff24 := by decide

/-- The Hadamard action is **not** in the monomial (`ℤ[ζ₈]`-integral) subgroup:
this is the element restored by the `ℤ[ζ₈] → ℤ[1/√2, ζ₈]` denominator change. -/
theorem permH_not_mem_8 : permH ∉ cliff8 := by decide

/-- **The order toggle.**  Over `ℤ[ζ₈]` the (projective) integral unitary
`Aut(L₃)` is the monomial Clifford group of order `8`; enlarging the ring to
`ℤ[1/√2, ζ₈]` restores the full single-qubit Clifford group of order `24`, the
extra elements being exactly those involving the Hadamard action `permH`
(which is excluded from the order-`8` group). -/
theorem clifford_order_toggle_8_to_24 :
    cliff8.card = 8 ∧ cliff24.card = 24 ∧ cliff8 ⊆ cliff24 ∧
      permH ∈ cliff24 ∧ permH ∉ cliff8 :=
  ⟨clifford8_card, clifford24_card, clifford8_subset_24, permH_mem_24, permH_not_mem_8⟩

/-! ## Part B — the dyadic ring `ℤ[1/√2, ζ₈]` and the Hadamard gate -/

open AutL3

/-- `√2 = ζ - ζ³ ∈ ℤ[ζ₈]`. -/
def sqrt2 : Z8 := Z8.zeta - Z8.zeta ^ 3

/-- `(√2)² = 2`. -/
theorem sqrt2_sq : sqrt2 * sqrt2 = 2 := by decide

/-- `√2` is **not** a unit in `ℤ[ζ₈]`: there is no `z` with `z·√2 = 1`.  Hence
`1/√2 ∉ ℤ[ζ₈]`, so the Hadamard gate `(1/√2)·[[1,1],[1,-1]]` is not integral over
`ℤ[ζ₈]`.  (Concretely `z·√2 = 1` forces the integer system `b-d=1, a+c=0, b+d=0,
c-a=0`, which has no solution.) -/
theorem sqrt2_not_unit : ¬ ∃ z : Z8, z * sqrt2 = 1 := by
  simp +decide [ sqrt2 ];
  intro x hx; have := congr_arg Z8.a hx; norm_num at this; have := congr_arg Z8.b hx; norm_num at this; have := congr_arg Z8.c hx; norm_num at this; have := congr_arg Z8.d hx; norm_num at this;
  erw [ show ( Z8.zeta - Z8.zeta ^ 3 : Z8 ) = ⟨ 0, 1, 0, -1 ⟩ from rfl ] at * ; norm_num at * ; omega

/-- The dyadic ring `ℤ[1/√2, ζ₈] = ℤ[ζ₈][1/√2]`, the localisation of `ℤ[ζ₈]`
inverting `√2`.  (Equivalently `ℤ[ζ₈][1/2]`, since `(√2)² = 2`.) -/
abbrev Z8h := Localization.Away sqrt2

/-- The structure map `ℤ[ζ₈] → ℤ[1/√2, ζ₈]`. -/
noncomputable def iota : Z8 →+* Z8h := algebraMap Z8 Z8h

/-- `1/√2 ∈ ℤ[1/√2, ζ₈]`. -/
noncomputable def invSqrt2 : Z8h := IsLocalization.Away.invSelf sqrt2

/-- `(1/√2)·√2 = 1` in the dyadic ring. -/
theorem invSqrt2_mul_sqrt2 : invSqrt2 * iota sqrt2 = 1 := by
  rw [mul_comm]
  exact IsLocalization.Away.mul_invSelf sqrt2

/-- `(1/√2)²·2 = 1` in the dyadic ring. -/
theorem invSqrt2_sq_mul_two : invSqrt2 * invSqrt2 * iota 2 = 1 := by
  have key : iota (2 : Z8) = iota sqrt2 * iota sqrt2 := by rw [← map_mul, sqrt2_sq]
  rw [key]
  have h := invSqrt2_mul_sqrt2
  calc invSqrt2 * invSqrt2 * (iota sqrt2 * iota sqrt2)
      = (invSqrt2 * iota sqrt2) * (invSqrt2 * iota sqrt2) := by ring
    _ = 1 := by rw [h]; ring

/-- The Hadamard gate over `ℤ[1/√2, ζ₈]`. -/
noncomputable def hadamard : Matrix (Fin 2) (Fin 2) Z8h :=
  invSqrt2 • !![1, 1; 1, -1]

/-- The Hadamard gate is symmetric, so `Hᵀ = H = H†` (its entries are real). -/
theorem hadamard_transpose : hadamard.transpose = hadamard := by
  ext i j; fin_cases i <;> fin_cases j <;> rfl

/-- **Hadamard is a unitary over `ℤ[1/√2, ζ₈]`.**  Being real and symmetric,
`H† = Hᵀ = H`, so unitarity `H·H† = 1` is the involution `H·H = 1`, which holds
because `(1/√2)²·2 = 1`.  Together with `sqrt2_not_unit`, this is the precise
sense in which the `ℤ[ζ₈] → ℤ[1/√2, ζ₈]` denominator change **restores Hadamard**:
the same matrix is a unitary lattice symmetry over the larger ring but is not
integral over `ℤ[ζ₈]`. -/
theorem hadamard_mul_self : hadamard * hadamard = 1 := by
  have hi2 : (iota 2 : Z8h) = 2 := by simp [iota, map_ofNat]
  have h2 : invSqrt2 * invSqrt2 * (2 : Z8h) = 1 := by rw [← hi2]; exact invSqrt2_sq_mul_two
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [hadamard, Matrix.mul_apply, Fin.sum_univ_two] <;>
    linear_combination h2

/-! ## The companion headline -/

/-- **The `ℤ[1/√2, ζ₈]` unitary `Aut(L₃)` is the full single-qubit Clifford group
(order 24), with Hadamard restored.**

This is the publishable strengthening companion to
`AutL3.finite_integral_su2_aut_L3` (the `ℤ[ζ₈]`-integral count `16`, projective
`8`).  Reading the conjuncts:

* `cliff24.card = 24` and `clifford24_generated`: the projective single-qubit
  Clifford group — realised by its faithful action on the six stabiliser states —
  has order `24` and is generated by the phase gate `S` and the Hadamard gate `H`.
* `cliff8.card = 8`, `cliff8 ⊆ cliff24`, `permH ∉ cliff8`: the `ℤ[ζ₈]`-integral
  *monomial* Clifford subgroup has order `8` and is a strict subgroup; the missing
  generator is exactly the Hadamard action.
* `hadamard * hadamard = 1`, `hadamard.transpose = hadamard`: the Hadamard matrix
  is a genuine (real, symmetric) unitary over `ℤ[1/√2, ζ₈]`.
* `¬ ∃ z, z * sqrt2 = 1`: but `1/√2 ∉ ℤ[ζ₈]`, so that same matrix is **not**
  integral over `ℤ[ζ₈]`.

Thus the one-line denominator change `ℤ[ζ₈] → ℤ[1/√2, ζ₈]` toggles the projective
order from `8` to `24`, surfacing Hadamard as the unique non-monomial Clifford
generator.  This is the companion to the integral Cliff+ T2 falsification
`grade1_n3_stratum_infinite`: both are integral-over-`ℤ[ζ₈]` restrictions of
standard answers, each excluding one feature (Hadamard here; the infinite
real-unit ladder `1+√2` there). -/
theorem aut_L3_unitary_over_Z_halfsqrt2_is_full_clifford :
    cliff24.card = 24 ∧
    sameSet (step^[6] [pid, permS, permH]) cliffList24 = true ∧
    cliff8.card = 8 ∧ cliff8 ⊆ cliff24 ∧ permH ∈ cliff24 ∧ permH ∉ cliff8 ∧
    hadamard * hadamard = 1 ∧ hadamard.transpose = hadamard ∧
    (¬ ∃ z : Z8, z * sqrt2 = 1) :=
  ⟨clifford24_card, clifford24_generated, clifford8_card, clifford8_subset_24,
    permH_mem_24, permH_not_mem_8, hadamard_mul_self, hadamard_transpose, sqrt2_not_unit⟩

end AutL3HalfSqrt2