import StabilizerBW.Roots.BW2

set_option maxHeartbeats 2000000

/-!
# The level-3 Barnes–Wall lattice `BW₃ = L₈` and the n=3 diagonal grades

This file builds the three-qubit (8-dimensional) Barnes–Wall lattice over `R = ℤ[ζ₈]`
and computes the λ-adic grades of the standard `n = 3` diagonal characters, extending
the two-qubit table of `Roots.BW2`.

We model an `8`-vector (basis order `000,001,…,111`) as a pair `Vec4 × Vec4`, the
"low" half (`positions 0..3`) and the "high" half (`positions 4..7`).  The level-3
Barnes–Wall recursion is the `(u, u + (1+i)·v)` construction:

```
BW₃ = L₈ = { (h₀, h₁) : h₀ ∈ L₄,  h₁ ∈ L₄,  h₀ - h₁ ∈ (1+i)·L₄ }.
```

Equivalently this is the iterated `(1+i)`-divisibility tower of depth three: each half
lies in `L₄`, and the two halves agree modulo `(1+i)·L₄`.  We give a decidable
divisibility criterion `inL3`, prove it is an `R`-submodule generated by the eight
vectors `Hᵢ`, and establish the reduction lemma "a diagonal operator preserves `L₈`
iff it preserves the eight generators."

The grade of a diagonal operator `D` is `g(D) = min k with λ^k·D·L₈ ⊆ L₈`; we package
it as `gradeLE3 D k := MapsToL3 (scale8 (λ^k) D)`, mirroring `Roots.BW2`.

## Results (all kernel-checked)

Transport : `g(CZ⊗I)=0`, `g(T⊗I⊗I)=1`, `g(CS⊗I)=2`, `g(cT⊗I)=3`, `g(T⊗T⊗I)=2`.

New three-qubit column :
* `g(CCZ) = 2`   (`e = 4·x₁x₂x₃`, `(d,ν) = (3,2)`),
* `g(CCS) = 4`   (`e = 2·x₁x₂x₃`, `(d,ν) = (3,1)`),
* `g(ccT) = 5`   (`e = 1·x₁x₂x₃`, `(d,ν) = (3,0)`),
* `g(x₁x₂+x₃ character) = 4`  (disjoint-support additivity: `3 + 1 = 4`).

These **falsify** the conjectured closed form `w(d,ν) = max(0, 2^d − 2^ν)` (which would
give `4, 6, 7`); see `Roots.BW3.closed_form_falsified`.  The actual data fit
`w(d,ν) = max(0, 2·d − 2^ν)`.
-/

namespace Roots
open Z8

/-- An 8-vector (basis order `000,…,111`): low half `0..3`, high half `4..7`. -/
abbrev Vec8 := Vec4 × Vec4

/-- Coordinatewise difference on `Vec4`. -/
def vsub4 (v w : Vec4) : Vec4 := ⟨v.c0 - w.c0, v.c1 - w.c1, v.c2 - w.c2, v.c3 - w.c3⟩

@[simp] theorem vsub4_c0 (v w) : (vsub4 v w).c0 = v.c0 - w.c0 := rfl
@[simp] theorem vsub4_c1 (v w) : (vsub4 v w).c1 = v.c1 - w.c1 := rfl
@[simp] theorem vsub4_c2 (v w) : (vsub4 v w).c2 = v.c2 - w.c2 := rfl
@[simp] theorem vsub4_c3 (v w) : (vsub4 v w).c3 = v.c3 - w.c3 := rfl

/-! ## Membership in `BW₃ = L₈` (decidable divisibility criterion) -/

/-- The "difference" predicate: `d ∈ (1+i)·L₄`, expanded as a divisibility tower.
`(1+i) ∣ dⱼ` (so `d/(1+i)` is integral), `(1+i)² ∣` the `L₄`-syndromes of `d`, and
`(1+i)³ ∣` the top syndrome. -/
def inDiff (d : Vec4) : Prop :=
  dvdOneI d.c0 ∧ dvdOneI d.c1 ∧ dvdOneI d.c2 ∧ dvdOneI d.c3 ∧
  Even2 (d.c0 + d.c1) ∧ Even2 (d.c2 + d.c3) ∧
  Even2 (d.c0 - d.c2) ∧ Even2 (d.c1 - d.c3) ∧
  Even2 (d.c0 + d.c1 - d.c2 - d.c3) ∧ dvdOneI (half (d.c0 + d.c1 - d.c2 - d.c3))

instance (d : Vec4) : Decidable (inDiff d) := by unfold inDiff Even2; infer_instance

/-- Membership in the level-3 Barnes–Wall lattice `BW₃ = L₈`. -/
def inL3 (v : Vec8) : Prop :=
  inL2crit v.1 ∧ inL2crit v.2 ∧ inDiff (vsub4 v.1 v.2)

instance (v : Vec8) : Decidable (inL3 v) := by unfold inL3; infer_instance

instance : DecidablePred inL3 := fun _ => inferInstance

/-! ## Division by `(1+i)` -/

/-- Exact division by `1+i`: `z·conj(1+i)/2 = z·(1-i)/2 = z/(1+i)` (exact when `(1+i)∣z`). -/
def divOneI (z : Z8) : Z8 := half (z * ⟨1, 0, -1, 0⟩)

/-
If `(1+i) ∣ z` then `(1+i)·divOneI z = z`.
-/
theorem oneI_mul_divOneI {z : Z8} (h : oneI ∣ z) : oneI * divOneI z = z := by
  obtain ⟨ y, rfl ⟩ := h;
  simp +decide [ divOneI, oneI ];
  simp +decide [ Z8.half ];
  congr <;> omega

/-
The recursive characterization: `inL3` is exactly the `(u, u+(1+i)v)` lattice.
-/
theorem inL3_iff_recursive (v : Vec8) :
    inL3 v ↔ inL2 v.1 ∧ inL2 v.2 ∧ ∃ w : Vec4, inL2 w ∧ vsub4 v.1 v.2 = vsmul4 oneI w := by
  constructor;
  · intro h;
    obtain ⟨w, hw⟩ : ∃ w : Vec4, vsub4 v.1 v.2 = vsmul4 oneI w := by
      have h_div : ∀ j : Fin 4, oneI ∣ (vsub4 v.1 v.2).c0 ∧ oneI ∣ (vsub4 v.1 v.2).c1 ∧ oneI ∣ (vsub4 v.1 v.2).c2 ∧ oneI ∣ (vsub4 v.1 v.2).c3 := by
        exact fun j => ⟨ by simpa only [ dvdOneI_iff ] using h.2.2.1, by simpa only [ dvdOneI_iff ] using h.2.2.2.1, by simpa only [ dvdOneI_iff ] using h.2.2.2.2.1, by simpa only [ dvdOneI_iff ] using h.2.2.2.2.2.1 ⟩;
      obtain ⟨w0, hw0⟩ : ∃ w0 : Z8, (vsub4 v.1 v.2).c0 = oneI * w0 := h_div 0 |>.1
      obtain ⟨w1, hw1⟩ : ∃ w1 : Z8, (vsub4 v.1 v.2).c1 = oneI * w1 := h_div 0 |>.2.1
      obtain ⟨w2, hw2⟩ : ∃ w2 : Z8, (vsub4 v.1 v.2).c2 = oneI * w2 := h_div 0 |>.2.2.1
      obtain ⟨w3, hw3⟩ : ∃ w3 : Z8, (vsub4 v.1 v.2).c3 = oneI * w3 := h_div 0 |>.2.2.2;
      exact ⟨ ⟨ w0, w1, w2, w3 ⟩, by ext <;> tauto ⟩;
    refine' ⟨ _, _, w, _, hw ⟩;
    · exact inL2_iff _ |>.2 h.1;
    · exact inL2_iff _ |>.2 h.2.1;
    · obtain ⟨hw1, hw2, hw3, hw4, hw5⟩ := h.2.2;
      simp_all +decide [ inL2_iff ];
      unfold inL2crit; simp_all +decide [ Even2 ] ;
      simp_all +decide [ Z8.dvdOneI, Z8.half ];
      grind;
  · simp +decide [ inL3, inL2_iff ];
    intro h1 h2 x hx h; simp_all +decide [ inL2crit, inDiff ] ;
    unfold Even2 at *; simp_all +decide [ Z8.dvdOneI ] ;
    simp_all +decide [ Z8.half ];
    omega

/-- The witness extracted from membership: a representative `w` of the difference. -/
theorem inL3_diff_exists {v : Vec8} (h : inL3 v) :
    ∃ w : Vec4, inL2 w ∧ vsub4 v.1 v.2 = vsmul4 oneI w := by
  exact ((inL3_iff_recursive v).1 h).2.2

theorem inL3_fst {v : Vec8} (h : inL3 v) : inL2 v.1 := ((inL3_iff_recursive v).1 h).1

/-! ## `R`-module structure on `R⁸` -/

/-- Scalar action of `R` on `R⁸`. -/
def vsmul8 (r : Z8) (v : Vec8) : Vec8 := (vsmul4 r v.1, vsmul4 r v.2)

/-- Vector addition on `R⁸`. -/
def vadd8 (v w : Vec8) : Vec8 := (vadd4 v.1 w.1, vadd4 v.2 w.2)

@[simp] theorem vsmul8_fst (r v) : (vsmul8 r v).1 = vsmul4 r v.1 := rfl
@[simp] theorem vsmul8_snd (r v) : (vsmul8 r v).2 = vsmul4 r v.2 := rfl
@[simp] theorem vadd8_fst (v w) : (vadd8 v w).1 = vadd4 v.1 w.1 := rfl
@[simp] theorem vadd8_snd (v w) : (vadd8 v w).2 = vadd4 v.2 w.2 := rfl

theorem inL3_add {v w : Vec8} (hv : inL3 v) (hw : inL3 w) : inL3 (vadd8 v w) := by
  obtain ⟨wv, hwv, hvw⟩ := inL3_diff_exists hv
  obtain ⟨ww, hww, hww'⟩ := inL3_diff_exists hw
  have h_diff : vsub4 (vadd4 v.1 w.1) (vadd4 v.2 w.2) = vsmul4 oneI (vadd4 wv ww) := by
    simp_all +decide [ vsub4, vadd4, vsmul4 ];
    simp_all +decide [ mul_add, add_sub_add_comm ];
  grind +suggestions

theorem inL3_vsmul (r : Z8) {v : Vec8} (hv : inL3 v) : inL3 (vsmul8 r v) := by
  convert ( inL3_iff_recursive ( vsmul8 r v ) ).2 _ using 1;
  refine' ⟨ _, _, _ ⟩;
  · exact inL2_vsmul r ( inL3_fst hv );
  · exact inL2_vsmul r ( inL3_fst hv |> fun h => ( inL3_iff_recursive v |>.1 hv ) |>.2.1 |> fun h => by tauto );
  · obtain ⟨ w, hw₁, hw₂ ⟩ := inL3_diff_exists hv;
    refine' ⟨ vsmul4 r w, _, _ ⟩;
    · exact inL2_vsmul r hw₁;
    · simp_all +decide [ vsub4, vsmul4, vsmul8 ];
      simp_all +decide [ ← mul_sub, mul_left_comm ]

/-! ## Generators -/

/-- The 8 generators of `L₈`: `(Gᵢ, Gᵢ)` (the "diagonal" copy of `L₄`) and
`(0, (1+i)·Gᵢ)` (the `(1+i)·L₄` difference part). -/
def H1 : Vec8 := (G1, G1)
def H2 : Vec8 := (G2, G2)
def H3 : Vec8 := (G3, G3)
def H4 : Vec8 := (G4, G4)
def H5 : Vec8 := (⟨0,0,0,0⟩, vsmul4 oneI G1)
def H6 : Vec8 := (⟨0,0,0,0⟩, vsmul4 oneI G2)
def H7 : Vec8 := (⟨0,0,0,0⟩, vsmul4 oneI G3)
def H8 : Vec8 := (⟨0,0,0,0⟩, vsmul4 oneI G4)

theorem inL3_H1 : inL3 H1 := by decide
theorem inL3_H2 : inL3 H2 := by decide
theorem inL3_H3 : inL3 H3 := by decide
theorem inL3_H4 : inL3 H4 := by decide
theorem inL3_H5 : inL3 H5 := by decide
theorem inL3_H6 : inL3 H6 := by decide
theorem inL3_H7 : inL3 H7 := by decide
theorem inL3_H8 : inL3 H8 := by decide

/-
Every `L₈` vector is an `R`-combination of `H₁,…,H₈`.
-/
theorem inL3_decompose {v : Vec8} (hv : inL3 v) :
    ∃ a1 a2 a3 a4 b1 b2 b3 b4 : Z8,
      v = vadd8 (vsmul8 a1 H1) (vadd8 (vsmul8 a2 H2) (vadd8 (vsmul8 a3 H3)
            (vadd8 (vsmul8 a4 H4) (vadd8 (vsmul8 b1 H5) (vadd8 (vsmul8 b2 H6)
              (vadd8 (vsmul8 b3 H7) (vsmul8 b4 H8))))))) := by
  -- Apply `inL3_fst` and `inL3_diff_exists` to get `v.1` and `w`.
  obtain ⟨hw₁, hw₂⟩ : inL2 v.1 ∧ ∃ w : Vec4, inL2 w ∧ vsub4 v.1 v.2 = vsmul4 oneI w := by
    exact ⟨ inL3_fst hv, inL3_diff_exists hv ⟩;
  obtain ⟨w, hw₃, hw₄⟩ := hw₂;
  obtain ⟨a1, a2, a3, a4, hv⟩ : ∃ a1 a2 a3 a4 : Z8, v.1 = vadd4 (vsmul4 a1 G1) (vadd4 (vsmul4 a2 G2) (vadd4 (vsmul4 a3 G3) (vsmul4 a4 G4))) := by
    obtain ⟨ a, al, be, hv ⟩ := inL2_decompose hw₁;
    exact ⟨ _, _, _, _, hv ⟩
  obtain ⟨b1, b2, b3, b4, hw⟩ : ∃ b1 b2 b3 b4 : Z8, w = vadd4 (vsmul4 b1 G1) (vadd4 (vsmul4 b2 G2) (vadd4 (vsmul4 b3 G3) (vsmul4 b4 G4))) := by
    exact inL2_decompose hw₃ |> fun ⟨ a, al, be, hw ⟩ => ⟨ _, _, _, _, hw ⟩;
  use a1, a2, a3, a4, -b1, -b2, -b3, -b4;
  simp_all +decide [ vsub4, vadd8, vsmul8, H1, H2, H3, H4, H5, H6, H7, H8 ];
  simp_all +decide [ vadd4, vsmul4, Prod.ext_iff ];
  exact Vec4.ext' ( by linear_combination -hw₄.1 ) ( by linear_combination -hw₄.2.1 ) ( by linear_combination -hw₄.2.2.1 ) ( by linear_combination -hw₄.2.2.2 )

/-! ## Diagonal operators and their grade -/

/-- A diagonal operator on `R⁸`. -/
abbrev Diag8 := Vec8

/-- The action of a diagonal operator (componentwise multiplication). -/
def dapply8 (D v : Vec8) : Vec8 := (dapply D.1 v.1, dapply D.2 v.2)

/-- Scaling a diagonal operator by a ring element. -/
def scale8 (r : Z8) (D : Vec8) : Vec8 := (scale4 r D.1, scale4 r D.2)

@[simp] theorem dapply8_fst (D v) : (dapply8 D v).1 = dapply D.1 v.1 := rfl
@[simp] theorem dapply8_snd (D v) : (dapply8 D v).2 = dapply D.2 v.2 := rfl
@[simp] theorem scale8_fst (r D) : (scale8 r D).1 = scale4 r D.1 := rfl
@[simp] theorem scale8_snd (r D) : (scale8 r D).2 = scale4 r D.2 := rfl

theorem dapply8_add (D v w : Vec8) :
    dapply8 D (vadd8 v w) = vadd8 (dapply8 D v) (dapply8 D w) := by
  simp only [dapply8, vadd8, dapply_add]

theorem dapply8_vsmul (D : Vec8) (r : Z8) (v : Vec8) :
    dapply8 D (vsmul8 r v) = vsmul8 r (dapply8 D v) := by
  simp only [dapply8, vsmul8, dapply_vsmul]

theorem dapply8_scale8 (r : Z8) (D v : Vec8) :
    dapply8 (scale8 r D) v = vsmul8 r (dapply8 D v) := by
  simp only [dapply8, scale8, vsmul8, dapply_scale4]

/-- A diagonal operator maps `L₈` into `L₈`. -/
def MapsToL3 (D : Vec8) : Prop := ∀ v, inL3 v → inL3 (dapply8 D v)

/-- **Reduction lemma.** A diagonal operator preserves `L₈` iff it preserves the eight
generators. -/
theorem mapsToL3_of_gens (D : Vec8)
    (h1 : inL3 (dapply8 D H1)) (h2 : inL3 (dapply8 D H2))
    (h3 : inL3 (dapply8 D H3)) (h4 : inL3 (dapply8 D H4))
    (h5 : inL3 (dapply8 D H5)) (h6 : inL3 (dapply8 D H6))
    (h7 : inL3 (dapply8 D H7)) (h8 : inL3 (dapply8 D H8)) : MapsToL3 D := by
  intro v hv
  obtain ⟨a1, a2, a3, a4, b1, b2, b3, b4, hdec⟩ := inL3_decompose hv
  rw [hdec]
  simp only [dapply8_add, dapply8_vsmul]
  exact inL3_add (inL3_vsmul _ h1) (inL3_add (inL3_vsmul _ h2) (inL3_add (inL3_vsmul _ h3)
    (inL3_add (inL3_vsmul _ h4) (inL3_add (inL3_vsmul _ h5) (inL3_add (inL3_vsmul _ h6)
      (inL3_add (inL3_vsmul _ h7) (inL3_vsmul _ h8)))))))

/-- `gradeLE3 D k`: the operator `λ^k · D` maps `L₈` into `L₈`. -/
def gradeLE3 (D : Vec8) (k : ℕ) : Prop := MapsToL3 (scale8 (Z8.lam ^ k) D)

theorem mapsToL3_scale (r : Z8) {D : Vec8} (h : MapsToL3 D) : MapsToL3 (scale8 r D) := by
  intro v hv
  rw [dapply8_scale8]
  exact inL3_vsmul r (h v hv)

/-- `gradeLE3` is upward closed. -/
theorem gradeLE3_succ {D : Vec8} {k : ℕ} (h : gradeLE3 D k) : gradeLE3 D (k + 1) := by
  unfold gradeLE3 at *
  have hsc : scale8 (Z8.lam ^ (k + 1)) D = scale8 Z8.lam (scale8 (Z8.lam ^ k) D) := by
    simp only [scale8, scale4, Prod.mk.injEq, Vec4.mk.injEq]
    refine ⟨⟨?_, ?_, ?_, ?_⟩, ?_, ?_, ?_, ?_⟩ <;> ring
  rw [hsc]
  exact mapsToL3_scale Z8.lam h

/-- `gradeLE3` is monotone in `k`. -/
theorem gradeLE3_of_le {D : Vec8} {a b : ℕ} (h : gradeLE3 D a) (hab : a ≤ b) :
    gradeLE3 D b := by
  induction hab with
  | refl => exact h
  | step _ ih => exact gradeLE3_succ ih

/-
`(1+i)³ ∣ λ⁶` (since `λ² ∼ 1+i`), so `λ⁶` lands every coordinate deep enough.
Every diagonal operator has grade `≤ 6`.
-/
theorem oneICube_dvd_lam_pow_six : (Z8.oneI * Z8.oneI * Z8.oneI) ∣ Z8.lam ^ 6 := by
  convert dvd_mul_right ( oneI * oneI * oneI ) ( Z8.uu * Z8.uu * Z8.uu ) using 1

theorem gradeLE3_top (D : Vec8) : gradeLE3 D 6 := by
  intro v hv; simp_all +decide [ inL3_iff_recursive, inL2_iff ] ;
  refine' ⟨ _, _, _ ⟩;
  · simp_all +decide [ inL2crit, Even2 ];
    simp_all +decide [ scale4, Z8.dvdOneI ];
    simp_all +decide [ ← even_iff_two_dvd, parity_simps ];
  · simp_all +decide [ inL2crit, dapply, scale4 ];
    simp_all +decide [ Z8.dvdOneI, Even2 ];
    simp_all +decide [ ← even_iff_two_dvd, parity_simps ];
  · refine' ⟨ _, _, _ ⟩;
    exact vsmul4 ( Z8.oneI * Z8.oneI * Z8.uu * Z8.uu * Z8.uu ) ( vsub4 ( dapply D.1 v.1 ) ( dapply D.2 v.2 ) );
    · unfold inL2crit; simp +decide [ Even2 ] ;
      unfold Z8.dvdOneI; simp +decide ;
      grind;
    · simp +decide [ vsub4, vsmul4, dapply, scale4 ];
      simp +decide [ mul_sub, sub_mul, mul_assoc, mul_comm, mul_left_comm ];
      exact ⟨ rfl, rfl, rfl, rfl ⟩

theorem gradeLE3_nonempty (D : Vec8) : ∃ k, gradeLE3 D k := ⟨6, gradeLE3_top D⟩

/-- The grade `g(D) = min k with λ^k·D·L₈ ⊆ L₈`. -/
noncomputable def grade3 (D : Vec8) : ℕ := sInf {k | gradeLE3 D k}

theorem gradeLE3_grade (D : Vec8) : gradeLE3 D (grade3 D) :=
  Nat.sInf_mem (gradeLE3_nonempty D)

theorem grade3_le {D : Vec8} {k : ℕ} (h : gradeLE3 D k) : grade3 D ≤ k :=
  Nat.sInf_le h

theorem grade3_eq_zero {D : Vec8} (h0 : gradeLE3 D 0) : grade3 D = 0 :=
  Nat.le_zero.mp (Nat.sInf_le h0)

/-- If `λ^m·D` preserves `L₈` but `λ^{m-1}·D` does not, the grade is exactly `m`. -/
theorem grade3_eq_of {D : Vec8} {m : ℕ} (hm : gradeLE3 D m)
    (hpred : ¬ gradeLE3 D (m - 1)) : grade3 D = m := by
  have hmem : grade3 D ∈ {k | gradeLE3 D k} := Nat.sInf_mem (gradeLE3_nonempty D)
  have hle : grade3 D ≤ m := Nat.sInf_le hm
  rcases Nat.lt_or_ge (grade3 D) m with h | h
  · exact absurd (gradeLE3_of_le hmem (by omega : grade3 D ≤ m - 1)) hpred
  · omega

/-! ## Sanity: the columns of `B^{⊗3}` lie in `L₈` -/

/-- The 8 columns of `B^{⊗3}` (`B = [[1+i,1],[0,1]]`) all lie in `BW₃ = L₈`,
anchoring that the divisibility criterion `inL3` captures the lattice generated by
`B^{⊗3}`. -/
theorem inL3_BcubeCols :
    inL3 (⟨Z8.oneI*Z8.oneI*Z8.oneI,0,0,0⟩, ⟨0,0,0,0⟩) ∧
    inL3 (⟨Z8.oneI*Z8.oneI,Z8.oneI*Z8.oneI,0,0⟩, ⟨0,0,0,0⟩) ∧
    inL3 (⟨Z8.oneI*Z8.oneI,0,Z8.oneI*Z8.oneI,0⟩, ⟨0,0,0,0⟩) ∧
    inL3 (⟨Z8.oneI,Z8.oneI,Z8.oneI,Z8.oneI⟩, ⟨0,0,0,0⟩) ∧
    inL3 (⟨Z8.oneI*Z8.oneI,0,0,0⟩, ⟨Z8.oneI*Z8.oneI,0,0,0⟩) ∧
    inL3 (⟨Z8.oneI,Z8.oneI,0,0⟩, ⟨Z8.oneI,Z8.oneI,0,0⟩) ∧
    inL3 (⟨Z8.oneI,0,Z8.oneI,0⟩, ⟨Z8.oneI,0,Z8.oneI,0⟩) ∧
    inL3 (⟨1,1,1,1⟩, ⟨1,1,1,1⟩) := by decide

/-! ## The witness for the lower bounds: `W₈ = (G₁, G₁) ∈ L₈` -/

/-- `W₈ = (G₁, G₁)`, i.e. the all-`±1` Reed–Muller vector `(1,-1,1,-1,1,-1,1,-1)`. -/
def W8 : Vec8 := (G1, G1)

theorem inL3_W8 : inL3 W8 := by decide

/-! ## T2 — transport of the embedded two-qubit grades -/

/-- `CZ ⊗ I = diag(1,1,1,1,1,1,-1,-1)`. -/
def CZI : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,-1,-1⟩)
/-- `T ⊗ I ⊗ I = diag(1,1,1,1,ζ,ζ,ζ,ζ)`. -/
def TII : Vec8 := (⟨1,1,1,1⟩, ⟨Z8.zeta,Z8.zeta,Z8.zeta,Z8.zeta⟩)
/-- `CS ⊗ I = diag(1,1,1,1,1,1,i,i)`. -/
def CSI : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,Z8.iu,Z8.iu⟩)
/-- `cT ⊗ I = diag(1,1,1,1,1,1,ζ,ζ)`. -/
def cTI : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,Z8.zeta,Z8.zeta⟩)
/-- `T ⊗ T ⊗ I = diag(1,1,ζ,ζ,ζ,ζ,ζ²,ζ²)`. -/
def TTI : Vec8 := (⟨1,1,Z8.zeta,Z8.zeta⟩, ⟨Z8.zeta,Z8.zeta,Z8.zeta^2,Z8.zeta^2⟩)

/-- **T2: `g(CZ ⊗ I) = 0`.** -/
theorem grade3_CZI : grade3 CZI = 0 := by
  apply grade3_eq_zero
  unfold gradeLE3
  simp only [pow_zero]
  apply mapsToL3_of_gens <;> decide

/-- **T2: `g(T ⊗ I ⊗ I) = 1`.** -/
theorem grade3_TII : grade3 TII = 1 := by
  apply grade3_eq_of (m := 1)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T2: `g(CS ⊗ I) = 2`.** -/
theorem grade3_CSI : grade3 CSI = 2 := by
  apply grade3_eq_of (m := 2)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T2: `g(cT ⊗ I) = 3`.** -/
theorem grade3_cTI : grade3 cTI = 3 := by
  apply grade3_eq_of (m := 3)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T2: `g(T ⊗ T ⊗ I) = 2`.** -/
theorem grade3_TTI : grade3 TTI = 2 := by
  apply grade3_eq_of (m := 2)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-! ## T3 — the genuinely three-qubit diagonal characters -/

/-- `CCZ = diag(1,1,1,1,1,1,1,-1)` (`e = 4·x₁x₂x₃`). -/
def CCZ : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,1,-1⟩)
/-- `CCS = diag(1,…,1,i)` (`e = 2·x₁x₂x₃`). -/
def CCS : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,1,Z8.iu⟩)
/-- `ccT = diag(1,…,1,ζ)` (`e = 1·x₁x₂x₃`). -/
def ccT : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,1,Z8.zeta⟩)
/-- The mixed character `e = x₁x₂ + x₃`: `diag(1,ζ,1,ζ,1,ζ,ζ,i)`. -/
def mixed : Vec8 := (⟨1,Z8.zeta,1,Z8.zeta⟩, ⟨1,Z8.zeta,Z8.zeta,Z8.iu⟩)

/-- **T3: `g(CCZ) = 2`.** -/
theorem grade3_CCZ : grade3 CCZ = 2 := by
  apply grade3_eq_of (m := 2)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T3: `g(CCS) = 4`.** -/
theorem grade3_CCS : grade3 CCS = 4 := by
  apply grade3_eq_of (m := 4)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T3: `g(ccT) = 5`.** -/
theorem grade3_ccT : grade3 ccT = 5 := by
  apply grade3_eq_of (m := 5)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-- **T3: `g(x₁x₂ + x₃ character) = 4`** (disjoint-support additivity `3 + 1 = 4`). -/
theorem grade3_mixed : grade3 mixed = 4 := by
  apply grade3_eq_of (m := 4)
  · unfold gradeLE3; apply mapsToL3_of_gens <;> decide
  · intro h; have := h W8 inL3_W8; revert this; decide

/-! ## T4 — the closed form is falsified -/

/-- The conjectured closed-form weight `w(d,ν) = max(0, 2^d − 2^ν)`. -/
def wConj (d nu : ℕ) : ℕ := max 0 (2 ^ d - 2 ^ nu)

/-- The revised closed-form weight `w(d,ν) = max(0, 2·d − 2^ν)` that fits all data. -/
def wFit (d nu : ℕ) : ℕ := max 0 (2 * d - 2 ^ nu)

/-- **T4(i): the conjectured closed form `max(0, 2^d − 2^ν)` is FALSIFIED.**
For `CCZ` (`d=3, ν=2`) it predicts `4` but the true grade is `2`; for `CCS` (`3,1`) it
predicts `6` but the true grade is `4`; for `ccT` (`3,0`) it predicts `7` but the true
grade is `5`. -/
theorem closed_form_falsified :
    grade3 CCZ ≠ wConj 3 2 ∧ grade3 CCS ≠ wConj 3 1 ∧ grade3 ccT ≠ wConj 3 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [grade3_CCZ]; decide
  · rw [grade3_CCS]; decide
  · rw [grade3_ccT]; decide

/-- **T4: the revised closed form `max(0, 2·d − 2^ν)` matches all three-qubit
single-monomial grades.** -/
theorem revised_form_holds :
    grade3 CCZ = wFit 3 2 ∧ grade3 CCS = wFit 3 1 ∧ grade3 ccT = wFit 3 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [grade3_CCZ]; decide
  · rw [grade3_CCS]; decide
  · rw [grade3_ccT]; decide

/-- **T4(ii): disjoint-support additivity holds** for `x₁x₂ + x₃`:
`g(x₁x₂+x₃) = g(cT⊗I) + g(T⊗I⊗I) = 3 + 1 = 4`. -/
theorem additivity_mixed : grade3 mixed = grade3 cTI + grade3 TII := by
  rw [grade3_mixed, grade3_cTI, grade3_TII]

end Roots