import StabilizerBW.Roots.BW3
import StabilizerBW.Roots.LinearBound

set_option maxHeartbeats 4000000

/-!
# The level-3 Barnes–Wall lattice `BW₄ = L₁₆` and the n=4 diagonal grades

This file builds the four-qubit (16-dimensional) Barnes–Wall lattice over `R = ℤ[ζ₈]`
and computes the λ-adic grades of the standard `n = 4` diagonal characters, extending
the three-qubit table of `Roots.BW3`.

We model a `16`-vector (basis order `0000,…,1111`) as a pair `Vec8 × Vec8`, the
"low" half (positions `0..7`, qubit-1 = 0) and the "high" half (positions `8..15`,
qubit-1 = 1).  The level-3 Barnes–Wall recursion is the `(u, u + (1+i)·v)`
construction one dimension up from `BW3.lean`:

```
BW₄ = L₁₆ = { (h₀, h₁) : h₀ ∈ L₈,  h₁ ∈ L₈,  h₀ - h₁ ∈ (1+i)·L₈ }.
```

We give a decidable divisibility criterion `inL4`, prove it is an `R`-submodule
generated by the sixteen vectors `Kᵢ`, and establish the reduction lemma "a diagonal
operator preserves `L₁₆` iff it preserves the sixteen generators."

The grade of a diagonal operator `D` is `g(D) = min k with λ^k·D·L₁₆ ⊆ L₁₆`; we
package it as `gradeLE4 D k := MapsToL4 (scale16 (λ^k) D)`, mirroring `Roots.BW3`.

## Results (all kernel-checked)

Transport (T2): `g(CCZ⊗I)=2`, `g(ccT⊗I)=5`, etc., all equal to the lower-dimensional
grade.

New four-qubit column (T3):
* `g(CCCZ) = 4`     (`e = 4·x₁x₂x₃x₄`, `(d,ν) = (4,2)`),
* `g(CCCS) = 6`     (`e = 2·x₁x₂x₃x₄`, `(d,ν) = (4,1)`),
* `g(cccT) = 7`     (`e = 1·x₁x₂x₃x₄`, `(d,ν) = (4,0)`),
* `g(x₁x₂x₃+x₄)=6`  (disjoint-support additivity: `5 + 1 = 6`),
* `g(x₁x₂+x₃x₄)=6`  (disjoint-support additivity: `3 + 3 = 6`).

These **confirm** the linear closed form `w(d,ν) = max(0, 2·d − 2^ν)` (`Roots.wFit`) at
`n = 4`; see `Roots.BW4.linear_form_audit_n4`.  The "max−1 structural prediction"
`max_e g(D_e) = 2·4 − 1 = 7 < 8` (the geometric ceiling `gradeLE4_top`) is settled by
`Roots.BW4.maxMinusOne_cccT`.
-/

namespace Roots
open Z8

/-- A 16-vector (basis order `0000,…,1111`): low half `0..7`, high half `8..15`. -/
abbrev Vec16 := Vec8 × Vec8

/-- Coordinatewise difference on `Vec8`. -/
def vsub8 (v w : Vec8) : Vec8 := (vsub4 v.1 w.1, vsub4 v.2 w.2)

@[simp] theorem vsub8_fst (v w : Vec8) : (vsub8 v w).1 = vsub4 v.1 w.1 := rfl
@[simp] theorem vsub8_snd (v w : Vec8) : (vsub8 v w).2 = vsub4 v.2 w.2 := rfl

/-! ## Exact division by `(1+i)` on vectors -/

/-- Coordinatewise exact division of a `Vec4` by `(1+i)`. -/
def vdivOneI4 (v : Vec4) : Vec4 := ⟨divOneI v.c0, divOneI v.c1, divOneI v.c2, divOneI v.c3⟩

/-- Coordinatewise exact division of a `Vec8` by `(1+i)`. -/
def vdivOneI8 (v : Vec8) : Vec8 := (vdivOneI4 v.1, vdivOneI4 v.2)

/-- `divOneI (oneI * x) = x`: dividing `(1+i)·x` by `(1+i)` recovers `x`. -/
theorem divOneI_oneI_mul (x : Z8) : divOneI (oneI * x) = x := by
  unfold divOneI Z8.half oneI
  apply Z8.ext' <;> simp [Z8.mul_a, Z8.mul_b, Z8.mul_c, Z8.mul_d] <;> omega

/-- `(1+i) ∣ (1+i)·x`, in decidable-parity form. -/
theorem dvdOneI_oneI_mul (x : Z8) : Z8.dvdOneI (oneI * x) := by
  rw [dvdOneI_iff]; exact ⟨x, rfl⟩

/-- Reconstructing a `(1+i)`-divisible `Vec8` from its `(1+i)`-quotient. -/
theorem vsmul8_oneI_vdivOneI8 {d : Vec8}
    (h0 : Z8.dvdOneI d.1.c0) (h1 : Z8.dvdOneI d.1.c1)
    (h2 : Z8.dvdOneI d.1.c2) (h3 : Z8.dvdOneI d.1.c3)
    (h4 : Z8.dvdOneI d.2.c0) (h5 : Z8.dvdOneI d.2.c1)
    (h6 : Z8.dvdOneI d.2.c2) (h7 : Z8.dvdOneI d.2.c3) :
    vsmul8 oneI (vdivOneI8 d) = d := by
  obtain ⟨d1, d2⟩ := d
  apply Prod.ext <;> apply Vec4.ext' <;>
    simp only [vsmul8, vdivOneI8, vsmul4_c0, vsmul4_c1, vsmul4_c2, vsmul4_c3, vdivOneI4]
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h0)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h1)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h2)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h3)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h4)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h5)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h6)
  · exact oneI_mul_divOneI ((dvdOneI_iff _).1 h7)

/-- `vdivOneI8 (vsmul8 oneI w) = w`: dividing `(1+i)·w` by `(1+i)` recovers `w`. -/
theorem vdivOneI8_vsmul8_oneI (w : Vec8) : vdivOneI8 (vsmul8 oneI w) = w := by
  obtain ⟨w1, w2⟩ := w
  apply Prod.ext <;> apply Vec4.ext' <;>
    simp only [vsmul8, vdivOneI8, vsmul4_c0, vsmul4_c1, vsmul4_c2, vsmul4_c3, vdivOneI4] <;>
    exact divOneI_oneI_mul _

/-! ## Membership in `BW₄ = L₁₆` (decidable divisibility criterion) -/

/-- The "difference" predicate: `d ∈ (1+i)·L₈`.  Every coordinate is `(1+i)`-divisible,
and the `(1+i)`-quotient `vdivOneI8 d` lies in `L₈`. -/
def inDiff8 (d : Vec8) : Prop :=
  Z8.dvdOneI d.1.c0 ∧ Z8.dvdOneI d.1.c1 ∧ Z8.dvdOneI d.1.c2 ∧ Z8.dvdOneI d.1.c3 ∧
  Z8.dvdOneI d.2.c0 ∧ Z8.dvdOneI d.2.c1 ∧ Z8.dvdOneI d.2.c2 ∧ Z8.dvdOneI d.2.c3 ∧
  inL3 (vdivOneI8 d)

instance (d : Vec8) : Decidable (inDiff8 d) := by unfold inDiff8; infer_instance

/-- Membership in the level-3 Barnes–Wall lattice `BW₄ = L₁₆`. -/
def inL4 (v : Vec16) : Prop :=
  inL3 v.1 ∧ inL3 v.2 ∧ inDiff8 (vsub8 v.1 v.2)

instance (v : Vec16) : Decidable (inL4 v) := by unfold inL4; infer_instance

instance : DecidablePred inL4 := fun _ => inferInstance

/-! ## `R`-module structure on `R¹⁶` -/

/-- Scalar action of `R` on `R¹⁶`. -/
def vsmul16 (r : Z8) (v : Vec16) : Vec16 := (vsmul8 r v.1, vsmul8 r v.2)

/-- Vector addition on `R¹⁶`. -/
def vadd16 (v w : Vec16) : Vec16 := (vadd8 v.1 w.1, vadd8 v.2 w.2)

@[simp] theorem vsmul16_fst (r v) : (vsmul16 r v).1 = vsmul8 r v.1 := rfl
@[simp] theorem vsmul16_snd (r v) : (vsmul16 r v).2 = vsmul8 r v.2 := rfl
@[simp] theorem vadd16_fst (v w) : (vadd16 v w).1 = vadd8 v.1 w.1 := rfl
@[simp] theorem vadd16_snd (v w) : (vadd16 v w).2 = vadd8 v.2 w.2 := rfl

/-- The recursive characterization: `inL4` is exactly the `(u, u+(1+i)v)` lattice. -/
theorem inL4_iff_recursive (v : Vec16) :
    inL4 v ↔ inL3 v.1 ∧ inL3 v.2 ∧
      ∃ w : Vec8, inL3 w ∧ vsub8 v.1 v.2 = vsmul8 oneI w := by
  constructor
  · rintro ⟨h1, h2, hd⟩
    refine ⟨h1, h2, vdivOneI8 (vsub8 v.1 v.2), hd.2.2.2.2.2.2.2.2, ?_⟩
    obtain ⟨e0, e1, e2, e3, e4, e5, e6, e7, _⟩ := hd
    exact (vsmul8_oneI_vdivOneI8 e0 e1 e2 e3 e4 e5 e6 e7).symm
  · rintro ⟨h1, h2, w, hw, hwd⟩
    refine ⟨h1, h2, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;> rw [hwd]
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · exact dvdOneI_oneI_mul _
    · rw [vdivOneI8_vsmul8_oneI]; exact hw

/-- The witness extracted from membership: a representative `w` of the difference. -/
theorem inL4_diff_exists {v : Vec16} (h : inL4 v) :
    ∃ w : Vec8, inL3 w ∧ vsub8 v.1 v.2 = vsmul8 oneI w :=
  ((inL4_iff_recursive v).1 h).2.2

theorem inL4_fst {v : Vec16} (h : inL4 v) : inL3 v.1 := ((inL4_iff_recursive v).1 h).1
theorem inL4_snd {v : Vec16} (h : inL4 v) : inL3 v.2 := ((inL4_iff_recursive v).1 h).2.1

/-- `vsmul8` over `vsub8`: scalars distribute over coordinatewise difference. -/
theorem vsub8_vsmul8 (r : Z8) (a b : Vec8) :
    vsub8 (vsmul8 r a) (vsmul8 r b) = vsmul8 r (vsub8 a b) := by
  apply Prod.ext <;> apply Vec4.ext' <;> simp [vsub8, vsmul8, vsub4, vsmul4] <;> ring

/-- `vsmul8` is associative in the scalar. -/
theorem vsmul8_vsmul8 (r s : Z8) (v : Vec8) :
    vsmul8 r (vsmul8 s v) = vsmul8 (r * s) v := by
  apply Prod.ext <;> apply Vec4.ext' <;> simp [vsmul8, vsmul4] <;> ring

/-- `vsub8` over `vadd8`: `(a+c) - (b+d) = (a-b) + (c-d)`. -/
theorem vsub8_vadd8 (a b c d : Vec8) :
    vsub8 (vadd8 a c) (vadd8 b d) = vadd8 (vsub8 a b) (vsub8 c d) := by
  apply Prod.ext <;> apply Vec4.ext' <;> simp [vsub8, vadd8, vsub4, vadd4] <;> ring

/-- `vsmul8` distributes over `vadd8`. -/
theorem vsmul8_vadd8 (r : Z8) (a b : Vec8) :
    vsmul8 r (vadd8 a b) = vadd8 (vsmul8 r a) (vsmul8 r b) := by
  apply Prod.ext <;> apply Vec4.ext' <;> simp [vsmul8, vadd8, vsmul4, vadd4] <;> ring

theorem inL4_add {v w : Vec16} (hv : inL4 v) (hw : inL4 w) : inL4 (vadd16 v w) := by
  obtain ⟨wv, hwv, hvw⟩ := inL4_diff_exists hv
  obtain ⟨ww, hww, hww'⟩ := inL4_diff_exists hw
  rw [inL4_iff_recursive]
  refine ⟨inL3_add (inL4_fst hv) (inL4_fst hw),
          inL3_add (inL4_snd hv) (inL4_snd hw),
          vadd8 wv ww, inL3_add hwv hww, ?_⟩
  simp only [vadd16_fst, vadd16_snd]
  rw [vsub8_vadd8, hvw, hww', vsmul8_vadd8]

theorem inL4_vsmul (r : Z8) {v : Vec16} (hv : inL4 v) : inL4 (vsmul16 r v) := by
  obtain ⟨w, hw, hwd⟩ := inL4_diff_exists hv
  rw [inL4_iff_recursive]
  refine ⟨inL3_vsmul r (inL4_fst hv), inL3_vsmul r (inL4_snd hv),
          vsmul8 r w, inL3_vsmul r hw, ?_⟩
  simp only [vsmul16_fst, vsmul16_snd]
  rw [vsub8_vsmul8, hwd, vsmul8_vsmul8, vsmul8_vsmul8, mul_comm]

/-! ## Generators -/

/-- The "zero" `Vec8`. -/
def Z8vec : Vec8 := (⟨0,0,0,0⟩, ⟨0,0,0,0⟩)

/-- The 16 generators of `L₁₆`: `(Hᵢ, Hᵢ)` (the "diagonal" copy of `L₈`) and
`(0, (1+i)·Hᵢ)` (the `(1+i)·L₈` difference part). -/
def K1 : Vec16 := (H1, H1)
def K2 : Vec16 := (H2, H2)
def K3 : Vec16 := (H3, H3)
def K4 : Vec16 := (H4, H4)
def K5 : Vec16 := (H5, H5)
def K6 : Vec16 := (H6, H6)
def K7 : Vec16 := (H7, H7)
def K8 : Vec16 := (H8, H8)
def K9  : Vec16 := (Z8vec, vsmul8 oneI H1)
def K10 : Vec16 := (Z8vec, vsmul8 oneI H2)
def K11 : Vec16 := (Z8vec, vsmul8 oneI H3)
def K12 : Vec16 := (Z8vec, vsmul8 oneI H4)
def K13 : Vec16 := (Z8vec, vsmul8 oneI H5)
def K14 : Vec16 := (Z8vec, vsmul8 oneI H6)
def K15 : Vec16 := (Z8vec, vsmul8 oneI H7)
def K16 : Vec16 := (Z8vec, vsmul8 oneI H8)

theorem inL4_K1 : inL4 K1 := by decide
theorem inL4_K2 : inL4 K2 := by decide
theorem inL4_K3 : inL4 K3 := by decide
theorem inL4_K4 : inL4 K4 := by decide
theorem inL4_K5 : inL4 K5 := by decide
theorem inL4_K6 : inL4 K6 := by decide
theorem inL4_K7 : inL4 K7 := by decide
theorem inL4_K8 : inL4 K8 := by decide
theorem inL4_K9 : inL4 K9 := by decide
theorem inL4_K10 : inL4 K10 := by decide
theorem inL4_K11 : inL4 K11 := by decide
theorem inL4_K12 : inL4 K12 := by decide
theorem inL4_K13 : inL4 K13 := by decide
theorem inL4_K14 : inL4 K14 := by decide
theorem inL4_K15 : inL4 K15 := by decide
theorem inL4_K16 : inL4 K16 := by decide

/-
Every `L₁₆` vector is an `R`-combination of `K₁,…,K₁₆`.
-/
theorem inL4_decompose {v : Vec16} (hv : inL4 v) :
    ∃ a1 a2 a3 a4 a5 a6 a7 a8 b1 b2 b3 b4 b5 b6 b7 b8 : Z8,
      v = vadd16 (vsmul16 a1 K1) (vadd16 (vsmul16 a2 K2) (vadd16 (vsmul16 a3 K3)
            (vadd16 (vsmul16 a4 K4) (vadd16 (vsmul16 a5 K5) (vadd16 (vsmul16 a6 K6)
              (vadd16 (vsmul16 a7 K7) (vadd16 (vsmul16 a8 K8)
                (vadd16 (vsmul16 b1 K9) (vadd16 (vsmul16 b2 K10) (vadd16 (vsmul16 b3 K11)
                  (vadd16 (vsmul16 b4 K12) (vadd16 (vsmul16 b5 K13) (vadd16 (vsmul16 b6 K14)
                    (vadd16 (vsmul16 b7 K15) (vsmul16 b8 K16))))))))))))))) := by
  obtain ⟨w, hw, hwd⟩ := inL4_diff_exists hv
  obtain ⟨a1, a2, a3, a4, a5, a6, a7, a8, hv1⟩ := inL3_decompose (inL4_fst hv)
  obtain ⟨b1, b2, b3, b4, b5, b6, b7, b8, hwdec⟩ := inL3_decompose hw
  refine ⟨a1, a2, a3, a4, a5, a6, a7, a8, -b1, -b2, -b3, -b4, -b5, -b6, -b7, -b8, ?_⟩
  apply Prod.ext;
  · simp +decide [ hv1, vadd16, vsmul16, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ];
    unfold vsmul8 Z8vec; simp +decide ;
    simp +decide [ vadd8, vadd4, vsmul4 ];
  · apply Prod.ext;
    · apply_fun (fun x => x.1) at hwd;
      simp +decide [ vadd16, vsmul16, vadd8, vsmul8, vsub8, vsmul4, vadd4, hv1, hwdec ] at hwd ⊢;
      simp +decide [ vsub4, H1, H2, H3, H4, H5, H6, H7, H8, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ] at hwd ⊢;
      exact Vec4.ext' ( by linear_combination -hwd.1 ) ( by linear_combination -hwd.2.1 ) ( by linear_combination -hwd.2.2.1 ) ( by linear_combination -hwd.2.2.2 );
    · apply Vec4.ext';
      · replace hwd := congr_arg ( fun x => x.2.c0 ) hwd; simp +decide [ vsub8, vsmul8 ] at hwd;
        simp +decide [ vadd16, vsmul16, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ] at *;
        simp +decide [ vadd8, vsmul8, H1, H2, H3, H4, H5, H6, H7, H8 ] at *;
        simp +decide [ vadd4, vsmul4, G1, G2, G3, G4 ] at hv1 hwdec hwd ⊢;
        grind +qlia;
      · simp +decide [ vadd16, vsmul16, vadd8, vsmul8, vadd4, vsmul4, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16, Z8vec, oneI ];
        apply_fun ( fun x => x.2.c1 ) at hwd; simp_all +decide [ vsub8, vsmul8 ] ;
        grind +qlia;
      · simp +decide [ vadd16, vsmul16, K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ];
        replace hwd := congr_arg ( fun x => x.2.c2 ) hwd ; simp_all +decide [ vsub8, vsmul8 ];
        grind;
      · replace hwd := congr_arg ( fun x => x.2.c3 ) hwd ; simp_all +decide [ vsub8, vadd8, vsmul8 ];
        simp_all +decide [ K1, K2, K3, K4, K5, K6, K7, K8, K9, K10, K11, K12, K13, K14, K15, K16 ];
        grind

/-! ## Diagonal operators and their grade -/

/-- A diagonal operator on `R¹⁶`. -/
abbrev Diag16 := Vec16

/-- The action of a diagonal operator (componentwise multiplication). -/
def dapply16 (D v : Vec16) : Vec16 := (dapply8 D.1 v.1, dapply8 D.2 v.2)

/-- Scaling a diagonal operator by a ring element. -/
def scale16 (r : Z8) (D : Vec16) : Vec16 := (scale8 r D.1, scale8 r D.2)

@[simp] theorem dapply16_fst (D v) : (dapply16 D v).1 = dapply8 D.1 v.1 := rfl
@[simp] theorem dapply16_snd (D v) : (dapply16 D v).2 = dapply8 D.2 v.2 := rfl
@[simp] theorem scale16_fst (r D) : (scale16 r D).1 = scale8 r D.1 := rfl
@[simp] theorem scale16_snd (r D) : (scale16 r D).2 = scale8 r D.2 := rfl

theorem dapply16_add (D v w : Vec16) :
    dapply16 D (vadd16 v w) = vadd16 (dapply16 D v) (dapply16 D w) := by
  simp only [dapply16, vadd16, dapply8_add]

theorem dapply16_vsmul (D : Vec16) (r : Z8) (v : Vec16) :
    dapply16 D (vsmul16 r v) = vsmul16 r (dapply16 D v) := by
  simp only [dapply16, vsmul16, dapply8_vsmul]

theorem dapply16_scale16 (r : Z8) (D v : Vec16) :
    dapply16 (scale16 r D) v = vsmul16 r (dapply16 D v) := by
  simp only [dapply16, scale16, vsmul16, dapply8_scale8]

/-- A diagonal operator maps `L₁₆` into `L₁₆`. -/
def MapsToL4 (D : Vec16) : Prop := ∀ v, inL4 v → inL4 (dapply16 D v)

/-- **Reduction lemma.** A diagonal operator preserves `L₁₆` iff it preserves the
sixteen generators. -/
theorem mapsToL4_of_gens (D : Vec16)
    (h1 : inL4 (dapply16 D K1)) (h2 : inL4 (dapply16 D K2))
    (h3 : inL4 (dapply16 D K3)) (h4 : inL4 (dapply16 D K4))
    (h5 : inL4 (dapply16 D K5)) (h6 : inL4 (dapply16 D K6))
    (h7 : inL4 (dapply16 D K7)) (h8 : inL4 (dapply16 D K8))
    (h9 : inL4 (dapply16 D K9)) (h10 : inL4 (dapply16 D K10))
    (h11 : inL4 (dapply16 D K11)) (h12 : inL4 (dapply16 D K12))
    (h13 : inL4 (dapply16 D K13)) (h14 : inL4 (dapply16 D K14))
    (h15 : inL4 (dapply16 D K15)) (h16 : inL4 (dapply16 D K16)) : MapsToL4 D := by
  intro v hv
  obtain ⟨a1,a2,a3,a4,a5,a6,a7,a8,b1,b2,b3,b4,b5,b6,b7,b8,hdec⟩ := inL4_decompose hv
  rw [hdec]
  simp only [dapply16_add, dapply16_vsmul]
  exact inL4_add (inL4_vsmul _ h1) (inL4_add (inL4_vsmul _ h2) (inL4_add (inL4_vsmul _ h3)
    (inL4_add (inL4_vsmul _ h4) (inL4_add (inL4_vsmul _ h5) (inL4_add (inL4_vsmul _ h6)
      (inL4_add (inL4_vsmul _ h7) (inL4_add (inL4_vsmul _ h8) (inL4_add (inL4_vsmul _ h9)
        (inL4_add (inL4_vsmul _ h10) (inL4_add (inL4_vsmul _ h11) (inL4_add (inL4_vsmul _ h12)
          (inL4_add (inL4_vsmul _ h13) (inL4_add (inL4_vsmul _ h14)
            (inL4_add (inL4_vsmul _ h15) (inL4_vsmul _ h16)))))))))))))))

/-- `gradeLE4 D k`: the operator `λ^k · D` maps `L₁₆` into `L₁₆`. -/
def gradeLE4 (D : Vec16) (k : ℕ) : Prop := MapsToL4 (scale16 (Z8.lam ^ k) D)

theorem mapsToL4_scale (r : Z8) {D : Vec16} (h : MapsToL4 D) : MapsToL4 (scale16 r D) := by
  intro v hv
  rw [dapply16_scale16]
  exact inL4_vsmul r (h v hv)

/-- `gradeLE4` is upward closed. -/
theorem gradeLE4_succ {D : Vec16} {k : ℕ} (h : gradeLE4 D k) : gradeLE4 D (k + 1) := by
  unfold gradeLE4 at *
  have hsc : scale16 (Z8.lam ^ (k + 1)) D = scale16 Z8.lam (scale16 (Z8.lam ^ k) D) := by
    simp only [scale16, scale8, scale4, Prod.mk.injEq, Vec4.mk.injEq]
    refine ⟨⟨⟨?_, ?_, ?_, ?_⟩, ?_, ?_, ?_, ?_⟩, ⟨?_, ?_, ?_, ?_⟩, ?_, ?_, ?_, ?_⟩ <;> ring
  rw [hsc]
  exact mapsToL4_scale Z8.lam h

/-- `gradeLE4` is monotone in `k`. -/
theorem gradeLE4_of_le {D : Vec16} {a b : ℕ} (h : gradeLE4 D a) (hab : a ≤ b) :
    gradeLE4 D b := by
  induction hab with
  | refl => exact h
  | step _ ih => exact gradeLE4_succ ih

/-! ## The universal top bound: every diagonal has grade `≤ 8` -/

/-
`(1+i)³ · R⁸ ⊆ L₈`: the conductor depth of the BW₃ lattice is exactly 3.
-/
theorem inL3_oneICube_smul (v : Vec8) :
    inL3 (vsmul8 (Z8.oneI * Z8.oneI * Z8.oneI) v) := by
  obtain ⟨ v1, v2 ⟩ := v;
  unfold inL3; simp +decide [ inL2crit, inDiff ] ;
  simp +decide [ Z8.dvdOneI, Z8.half, Even2 ];
  grind

/-
Every diagonal operator on `R¹⁶` has grade `≤ 8` (geometric ceiling `2·4`).
-/
theorem gradeLE4_top (D : Vec16) : gradeLE4 D 8 := by
  intro v hv;
  rw [inL4_iff_recursive];
  refine' ⟨ _, _, _ ⟩;
  · have h1 : gradeLE3 D.1 8 := by
      exact gradeLE3_of_le ( gradeLE3_top _ ) ( by decide );
    exact h1 v.1 ( inL4_fst hv );
  · convert gradeLE3_of_le ( gradeLE3_top D.2 ) ( show 8 ≥ 6 by decide ) v.2 ( inL4_snd hv ) using 1;
  · refine' ⟨ vsmul8 ( oneI * oneI * oneI ) ( vsmul8 ( Z8.uu ^ 4 ) ( vsub8 ( dapply8 D.1 v.1 ) ( dapply8 D.2 v.2 ) ) ), _, _ ⟩;
    · convert inL3_oneICube_smul _ using 1;
    · simp +decide [ dapply16, scale16, dapply8_scale8, vsmul8_vsmul8 ];
      convert vsub8_vsmul8 _ _ _ using 2

theorem gradeLE4_nonempty (D : Vec16) : ∃ k, gradeLE4 D k := ⟨8, gradeLE4_top D⟩

/-- The grade `g(D) = min k with λ^k·D·L₁₆ ⊆ L₁₆`. -/
noncomputable def grade4 (D : Vec16) : ℕ := sInf {k | gradeLE4 D k}

theorem gradeLE4_grade (D : Vec16) : gradeLE4 D (grade4 D) :=
  Nat.sInf_mem (gradeLE4_nonempty D)

theorem grade4_le {D : Vec16} {k : ℕ} (h : gradeLE4 D k) : grade4 D ≤ k :=
  Nat.sInf_le h

theorem grade4_eq_zero {D : Vec16} (h0 : gradeLE4 D 0) : grade4 D = 0 :=
  Nat.le_zero.mp (Nat.sInf_le h0)

/-- If `λ^m·D` preserves `L₁₆` but `λ^{m-1}·D` does not, the grade is exactly `m`. -/
theorem grade4_eq_of {D : Vec16} {m : ℕ} (hm : gradeLE4 D m)
    (hpred : ¬ gradeLE4 D (m - 1)) : grade4 D = m := by
  have hmem : grade4 D ∈ {k | gradeLE4 D k} := Nat.sInf_mem (gradeLE4_nonempty D)
  have hle : grade4 D ≤ m := Nat.sInf_le hm
  rcases Nat.lt_or_ge (grade4 D) m with h | h
  · exact absurd (gradeLE4_of_le hmem (by omega : grade4 D ≤ m - 1)) hpred
  · omega

theorem grade4_le_top (D : Vec16) : grade4 D ≤ 8 := grade4_le (gradeLE4_top D)

/-! ## Sanity: the columns of `B^{⊗4}` lie in `L₁₆` -/

/-- A few columns of `B^{⊗4}` lie in `BW₄ = L₁₆`, anchoring `inL4`. -/
theorem inL4_BcubeCols :
    inL4 ((⟨Z8.oneI*Z8.oneI*Z8.oneI*Z8.oneI,0,0,0⟩, ⟨0,0,0,0⟩),
          (⟨0,0,0,0⟩, ⟨0,0,0,0⟩)) ∧
    inL4 ((⟨1,1,1,1⟩, ⟨1,1,1,1⟩), (⟨1,1,1,1⟩, ⟨1,1,1,1⟩)) := by decide

/-! ## The witness for the lower bounds: `W₁₆ = (W₈, W₈) ∈ L₁₆` -/

/-- `W₁₆ = (W₈, W₈)`, the all-`±1` Reed–Muller vector extending `W₈`. -/
def W16 : Vec16 := (W8, W8)

theorem inL4_W16 : inL4 W16 := by decide

/-! ## Helper `Vec8` building blocks for the n=4 characters -/

/-- The all-ones `Vec8` (the identity diagonal on 3 qubits). -/
def ones8 : Vec8 := (⟨1,1,1,1⟩, ⟨1,1,1,1⟩)

/-! ## T2 — transport of the embedded three-qubit grades -/

/-- `CCZ ⊗ I` (`CCZ` on qubits 1-3, idle qubit 4). -/
def CCZI : Vec16 := (CCZ, CCZ)
/-- `ccT ⊗ I` (`ccT` on qubits 1-3, idle qubit 4). -/
def ccTI : Vec16 := (ccT, ccT)

/-- **T2: `g(CCZ ⊗ I) = g(CCZ) = 2`.** -/
theorem grade4_CCZI : grade4 CCZI = 2 := by
  apply grade4_eq_of (m := 2)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T2: `g(ccT ⊗ I) = g(ccT) = 5`.** -/
theorem grade4_ccTI : grade4 ccTI = 5 := by
  apply grade4_eq_of (m := 5)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T2: embedding preserves the grade for `CCZ`.** -/
theorem embed_CCZ : grade4 CCZI = grade3 CCZ := by rw [grade4_CCZI, grade3_CCZ]
/-- **T2: embedding preserves the grade for `ccT`.** -/
theorem embed_ccT : grade4 ccTI = grade3 ccT := by rw [grade4_ccTI, grade3_ccT]

/-! ## T3 — the genuinely four-qubit diagonal characters -/

/-- `CCCZ = diag(1,…,1,-1)` (`e = 4·x₁x₂x₃x₄`), `(d,ν) = (4,2)`. -/
def CCCZ : Vec16 := (ones8, (⟨1,1,1,1⟩, ⟨1,1,1,-1⟩))
/-- `CCCS = diag(1,…,1,i)` (`e = 2·x₁x₂x₃x₄`), `(d,ν) = (4,1)`. -/
def CCCS : Vec16 := (ones8, (⟨1,1,1,1⟩, ⟨1,1,1,Z8.iu⟩))
/-- `cccT = diag(1,…,1,ζ)` (`e = 1·x₁x₂x₃x₄`), `(d,ν) = (4,0)`. -/
def cccT : Vec16 := (ones8, (⟨1,1,1,1⟩, ⟨1,1,1,Z8.zeta⟩))
/-- The mixed character `e = x₁x₂x₃ + x₄` (disjoint supports). -/
def mixed31 : Vec16 :=
  ((⟨1,Z8.zeta,1,Z8.zeta⟩, ⟨1,Z8.zeta,1,Z8.zeta⟩),
   (⟨1,Z8.zeta,1,Z8.zeta⟩, ⟨1,Z8.zeta,Z8.zeta,Z8.iu⟩))
/-- The mixed character `e = x₁x₂ + x₃x₄` (two disjoint degree-2 monomials). -/
def mixed22 : Vec16 :=
  ((⟨1,1,1,Z8.zeta⟩, ⟨1,1,1,Z8.zeta⟩),
   (⟨1,1,1,Z8.zeta⟩, ⟨Z8.zeta,Z8.zeta,Z8.zeta,Z8.iu⟩))

/-- **T3: `g(CCCZ) = 4`.** -/
theorem grade4_CCCZ : grade4 CCCZ = 4 := by
  apply grade4_eq_of (m := 4)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T3: `g(CCCS) = 6`.** -/
theorem grade4_CCCS : grade4 CCCS = 6 := by
  apply grade4_eq_of (m := 6)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T3: `g(cccT) = 7`.** -/
theorem grade4_cccT : grade4 cccT = 7 := by
  apply grade4_eq_of (m := 7)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T3: `g(x₁x₂x₃ + x₄) = 6`** (disjoint-support additivity `5 + 1 = 6`). -/
theorem grade4_mixed31 : grade4 mixed31 = 6 := by
  apply grade4_eq_of (m := 6)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-- **T3: `g(x₁x₂ + x₃x₄) = 6`** (disjoint-support additivity `3 + 3 = 6`). -/
theorem grade4_mixed22 : grade4 mixed22 = 6 := by
  apply grade4_eq_of (m := 6)
  · unfold gradeLE4; apply mapsToL4_of_gens <;> decide
  · intro h; have := h W16 inL4_W16; revert this; decide

/-! ## T4 — the closed-form verdict at n = 4 -/

/-- **T4: the conjectured closed form `max(0, 2^d − 2^ν)` remains FALSIFIED at n=4.**
For `cccT` (`d=4, ν=0`) it predicts `2^4 − 1 = 15` but the true grade is `7`. -/
theorem closed_form_falsified_n4 :
    grade4 CCCZ ≠ wConj 4 2 ∧ grade4 CCCS ≠ wConj 4 1 ∧ grade4 cccT ≠ wConj 4 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [grade4_CCCZ]; decide
  · rw [grade4_CCCS]; decide
  · rw [grade4_cccT]; decide

/-- **T4 (audit, exact form).** Every four-qubit single-monomial diagonal character
satisfies `g = wFit d ν = max(0, 2d − 2^ν)`. -/
theorem linear_form_audit_n4 :
    grade4 CCCZ = wFit 4 2 ∧ grade4 CCCS = wFit 4 1 ∧ grade4 cccT = wFit 4 0 := by
  refine ⟨?_, ?_, ?_⟩
  · rw [grade4_CCCZ]; decide
  · rw [grade4_CCCS]; decide
  · rw [grade4_cccT]; decide

/-- **T4 (audit, upper bound form).** -/
theorem linear_bound_audit_n4 :
    grade4 CCCZ ≤ wFit 4 2 ∧ grade4 CCCS ≤ wFit 4 1 ∧ grade4 cccT ≤ wFit 4 0 := by
  obtain ⟨h1, h2, h3⟩ := linear_form_audit_n4
  exact ⟨h1.le, h2.le, h3.le⟩

/-- **T4 (additivity).** Both disjoint-support mixed cases saturate the additive bound:
`g(x₁x₂x₃+x₄) = wFit 3 0 + wFit 1 0 = 5 + 1 = 6` and
`g(x₁x₂+x₃x₄) = wFit 2 0 + wFit 2 0 = 3 + 3 = 6`. -/
theorem linear_bound_mixed_n4 :
    grade4 mixed31 = wFit 3 0 + wFit 1 0 ∧ grade4 mixed22 = wFit 2 0 + wFit 2 0 := by
  refine ⟨?_, ?_⟩
  · rw [grade4_mixed31]; decide
  · rw [grade4_mixed22]; decide

/-! ## T5 — the "max − 1" structural prediction -/

/-- **T5: the max−1 structural prediction at n=4.** The genuinely four-qubit monomial
`cccT` attains grade `2·4 − 1 = 7`, exactly one below the geometric ceiling
`gradeLE4_top : grade4 D ≤ 8`.  Thus the maximal single-monomial grade sits one rung
below the lattice bound, which is reached only by non-monomial combinations. -/
theorem maxMinusOne_cccT : grade4 cccT = 2 * 4 - 1 ∧ grade4 cccT < 8 := by
  refine ⟨by rw [grade4_cccT], ?_⟩
  rw [grade4_cccT]; decide

end Roots