import Mathlib
import StabilizerBW.MenuBridge

/-!
# MenuBandwidthAllN / CliffordMenuAllN — T1: the `n`-qubit Clifford menu and its stabilizer bound

This file lifts the four-qubit Clifford-menu construction of
`StabilizerBW.MenuBandwidthN4.CliffordMenuN4` to **all** `n`: the menu is the
`3n` single-qubit Pauli observables `{X_q, Y_q, Z_q : q ∈ Fin n}`, indexed by
`Idx n = Fin n × Fin 3` (`(qubit, axis)`).

The facet functional is the all-ones functional `W = Σ_{q,a} ⟨P^a_q⟩` and the key
structural fact — the all-`n` analogue of
`CliffordMenuN4.octahedron_facet_stab_bound4` — is proved here directly via the
octahedron-norm argument lifted to `n` qubits:

* `MenuBandwidthAllN.octahedron_facet_stab_boundN` — every `n`-qubit stabilizer
  state satisfies `W ≤ n`.  Thus `classicalBound = n` is a genuine valid bound,
  matching the per-qubit ℓ¹ Bloch bound summed over `n` qubits.

We also package the all-ones facet as a `MenuBridge.Facet (3 * n)`:

* `MenuBandwidthAllN.cliffordFacetN` — coefficient `1` on each of the `3n`
  observables, classical bound `n`.
* `MenuBandwidthAllN.cliffordFacetN_S` — `S = ∑_k |α_k| = 3n`.
* `MenuBandwidthAllN.cliffordFacetN_N` — `N = 2S = 6n`.

The development is entirely over `ℝ` (the convex-geometry layer): a profile
`e : Idx n → ℝ` records the menu expectation values `⟨M_i⟩ ∈ [-1,1]`, and the
stabilizer side uses the fact that the realisable profiles form the convex hull of
the deterministic octahedron-vertex profiles.
-/

open scoped BigOperators

namespace MenuBandwidthAllN

/-! ## §1  Menu facet functionals and the stabilizer polytope (generic) -/

section General

variable {ι : Type*} [Fintype ι]

/-- The menu **facet functional** `∑ᵢ αᵢ ⟨Mᵢ⟩` evaluated on an expectation
    profile `e`. -/
def facetValue (α : ι → ℝ) (e : ι → ℝ) : ℝ := ∑ i, α i * e i

/-- A profile `e` lies in the **stabilizer polytope** generated by a finite
    vertex set `S` if it is a convex combination of the vertices. -/
def InPolytope (S : Finset (ι → ℝ)) (e : ι → ℝ) : Prop :=
  ∃ w : (ι → ℝ) → ℝ,
    (∀ p, 0 ≤ w p) ∧ (∑ p ∈ S, w p = 1) ∧ (∀ i, e i = ∑ p ∈ S, w p * p i)

/-- **Convexity bound:** if the facet functional is `≤ C` on every vertex, it is
    `≤ C` on the whole polytope. -/
theorem facetValue_le_of_polytope (α : ι → ℝ) (C : ℝ) (S : Finset (ι → ℝ))
    (hS : ∀ p ∈ S, facetValue α p ≤ C) {e : ι → ℝ} (he : InPolytope S e) :
    facetValue α e ≤ C := by
  obtain ⟨w, hw0, hw1, hwe⟩ := he
  have h_subst : facetValue α e = ∑ p ∈ S, w p * facetValue α p := by
    simp only [facetValue, hwe, Finset.mul_sum]
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl (fun p _ => Finset.sum_congr rfl (fun i _ => by ring))
  rw [h_subst]
  calc ∑ p ∈ S, w p * facetValue α p
      ≤ ∑ p ∈ S, w p * C :=
        Finset.sum_le_sum (fun p hp => mul_le_mul_of_nonneg_left (hS p hp) (hw0 p))
    _ = C := by rw [← Finset.sum_mul, hw1, one_mul]

end General

/-! ## §2  The concrete `n`-qubit Clifford-menu game

Observables are indexed by `(q, a) : Fin n × Fin 3`: `q` the qubit, `a ∈ {0,1,2}`
the Pauli axis `X, Y, Z`.  `3n` single-qubit Pauli observables, all-ones facet
functional `W = Σ_{q,a} ⟨P^a_q⟩`, threshold `C = n`. -/

/-- Observable index: `(qubit, axis)`, `3n` in total. -/
abbrev Idx (n : ℕ) := Fin n × Fin 3

/-- The all-ones facet coefficients `αₖ = 1`. -/
def coeffOneN (n : ℕ) : Idx n → ℝ := fun _ => 1

/-- The facet threshold `C = n` (the per-qubit ℓ¹ Bloch bound summed over `n`
    qubits; the maximum of `W` over the `n`-qubit stabilizer polytope). -/
def menuCN (n : ℕ) : ℝ := n

/-- A single-qubit octahedron vertex: axis `a` with sign `s`: `±1` on the fixed
    axis, `0` on the two anticommuting axes. -/
noncomputable def octVertex (a : Fin 3) (s : Bool) : Fin 3 → ℝ :=
  fun b => if b = a then (if s then (1 : ℝ) else -1) else 0

/-- An `n`-qubit stabilizer vertex profile: a per-qubit octahedron vertex. -/
noncomputable def menuVertex {n : ℕ} (c : Fin n → Fin 3 × Bool) : Idx n → ℝ :=
  fun qa => octVertex (c qa.1).1 (c qa.1).2 qa.2

/-- The vertex set of the `n`-qubit stabilizer polytope (the `6ⁿ` deterministic
    profiles). -/
noncomputable def menuVertices (n : ℕ) : Finset (Idx n → ℝ) :=
  Finset.image menuVertex Finset.univ

/-! ### PLₙ forcing -/

theorem octVertex_abs_le_one (a : Fin 3) (s : Bool) (b : Fin 3) :
    |octVertex a s b| ≤ 1 := by
  unfold octVertex; split_ifs <;> norm_num

/-- The single-qubit facet value `⟨X⟩+⟨Y⟩+⟨Z⟩` of a forced (octahedron-vertex)
    profile is `±1`, hence `≤ 1`. -/
theorem octVertex_sum_le_one (a : Fin 3) (s : Bool) :
    ∑ b, octVertex a s b ≤ 1 := by
  unfold octVertex; split_ifs <;> norm_num

/-! ### Part (a): the stabilizer facet bound -/

/-- The facet value of a single `n`-qubit stabilizer vertex is `≤ n`. -/
theorem menuVertex_facet_le {n : ℕ} (c : Fin n → Fin 3 × Bool) :
    facetValue (coeffOneN n) (menuVertex c) ≤ menuCN n := by
  have h : facetValue (coeffOneN n) (menuVertex c)
      = ∑ q : Fin n, ∑ a : Fin 3, octVertex (c q).1 (c q).2 a := by
    unfold facetValue coeffOneN menuVertex
    rw [Fintype.sum_prod_type]; simp
  rw [h]
  calc ∑ q : Fin n, ∑ a : Fin 3, octVertex (c q).1 (c q).2 a
      ≤ ∑ _q : Fin n, (1:ℝ) := Finset.sum_le_sum (fun q _ => octVertex_sum_le_one _ _)
    _ = menuCN n := by simp [menuCN]

/-- **T1 (proved):** every profile in the `n`-qubit stabilizer polytope satisfies
    the menu facet inequality `W ≤ n`. -/
theorem octahedron_facet_stab_boundN (n : ℕ) {e : Idx n → ℝ}
    (he : InPolytope (menuVertices n) e) :
    facetValue (coeffOneN n) e ≤ menuCN n := by
  refine facetValue_le_of_polytope (coeffOneN n) (menuCN n) (menuVertices n) ?_ he
  intro p hp
  rw [menuVertices, Finset.mem_image] at hp
  obtain ⟨c, _, rfl⟩ := hp
  exact menuVertex_facet_le c

/-! ### The threshold is attained: `C = n` is the exact maximum -/

/-- The all-`+Z` stabilizer vertex: every qubit fixed to the `Z = +1` eigenstate. -/
noncomputable def allZPlus (n : ℕ) : Idx n → ℝ := menuVertex (fun _ => (2, true))

/-- The all-`+Z` vertex attains `W = n`, so the bound `C = n` is tight. -/
theorem allZPlus_facet_value (n : ℕ) :
    facetValue (coeffOneN n) (allZPlus n) = menuCN n := by
  unfold facetValue coeffOneN allZPlus menuVertex octVertex menuCN
  simp only [one_mul]
  rw [Fintype.sum_prod_type]
  simp

/-! ## §3  The all-ones facet, packaged for the bandwidth bridge -/

/-- The canonical indexing equivalence `Idx n = Fin n × Fin 3 ≃ Fin (3 * n)`. -/
def idxN (n : ℕ) : Idx n ≃ Fin (3 * n) := finProdFinEquiv.trans (finCongr (by ring))

/-- **T1: the all-ones facet at the `n`-qubit Clifford menu.**  Coefficient `1`
on each of the `3n` single-qubit Pauli observables, classical bound `C = n`. -/
def cliffordFacetN (n : ℕ) : MenuBridge.Facet (3 * n) where
  coeff := fun _ => 1
  classicalBound := n

/-- **T1: `S = ∑_k |α_k| = 3n`.** -/
theorem cliffordFacetN_S (n : ℕ) : (cliffordFacetN n).S = 3 * (n : ℝ) := by
  unfold MenuBridge.Facet.S cliffordFacetN; simp [mul_comm]

/-- **T1: `N = 2S = 6n`.** -/
theorem cliffordFacetN_N (n : ℕ) : (cliffordFacetN n).N = 6 * (n : ℝ) := by
  unfold MenuBridge.Facet.N; rw [cliffordFacetN_S]; ring

/-- The half-width is positive for `n ≥ 1`, so the facet is nondegenerate. -/
theorem cliffordFacetN_S_pos (n : ℕ) (hn : 1 ≤ n) : 0 < (cliffordFacetN n).S := by
  rw [cliffordFacetN_S]
  have : (0:ℝ) < n := by exact_mod_cast (by omega : 0 < n)
  linarith

/-- **T1 (functional identification):** the facet functional `L` evaluated on the
profile lifted through `idxN` equals the menu functional `W = Σ_{q,a} ⟨P^a_q⟩`. -/
theorem cliffordFacetN_L_eq_facetValue (n : ℕ) (E : Idx n → ℝ) :
    (cliffordFacetN n).L (fun k => E ((idxN n).symm k)) = facetValue (coeffOneN n) E := by
  unfold MenuBridge.Facet.L cliffordFacetN facetValue coeffOneN
  rw [← Equiv.sum_comp (idxN n) (fun k => (1 : ℝ) * E ((idxN n).symm k))]
  simp

/-- The facet violation of the lifted profile equals the menu violation
`W(E) − n`. -/
theorem cliffordFacetN_violation_eq (n : ℕ) (E : Idx n → ℝ) :
    (cliffordFacetN n).violation (fun k => E ((idxN n).symm k))
      = facetValue (coeffOneN n) E - menuCN n := by
  unfold MenuBridge.Facet.violation
  rw [cliffordFacetN_L_eq_facetValue]
  simp [cliffordFacetN, menuCN]

/-- **T1 (operational stabilizer bound):** every `n`-qubit stabilizer profile has
nonpositive facet violation — the `Facet`-level form of
`octahedron_facet_stab_boundN`. -/
theorem cliffordFacetN_violation_le_zero_of_stab (n : ℕ) {E : Idx n → ℝ}
    (he : InPolytope (menuVertices n) E) :
    (cliffordFacetN n).violation (fun k => E ((idxN n).symm k)) ≤ 0 := by
  rw [cliffordFacetN_violation_eq]
  have := octahedron_facet_stab_boundN n he
  linarith

end MenuBandwidthAllN
