import StabilizerBW.Qutrit.EisensteinToy.EisensteinIntegers

/-!
# The qutrit Barnes–Wall analogue at level 1 over `ℤ[ω]`

The qubit level-3 Barnes–Wall lattice is `L₃ = {(x,y) ∈ ℤ[ζ₈]² : (1+i) ∣ (x+y)}`, where the
"doubling prime" `1+i` is the prime above the dimension `d = 2`.  The natural qutrit analogue
at dimension `d = 3` uses the prime above `3` in the Eisenstein integers, which is `λ₃ = 1 - ω`
itself, giving

  `L = {(x,y) ∈ ℤ[ω]² : λ₃ ∣ (x+y)}`.

We give `L` a decidable membership criterion (`3 ∣ (re + im)` of the coordinate sum), prove it
is an `ℤ[ω]`-submodule generated by `g₁ = (1,-1)` and `g₂ = (0, λ₃)`, set up `2×2` matrices over
`ℤ[ω]` with their action, and define the qutrit grade `g(M) = min k with λ₃^k·M·L ⊆ L`.

A first structural observation is recorded here (and elaborated in the test files):
* `gradeEMat_diag_omega` — `diag(1, ω)` has grade `0` (it is `≡ I (mod λ₃)`),
* `gradeEMat_diag_negOne` — `diag(1, -1)` has grade `1`.

The second is already a *qutrit-specific deviation*: `-1` is a qutrit Clifford phase, yet over
this Eisenstein lattice it has nonzero grade, unlike the qubit case where the Clifford phases are
grade-`0` automorphisms.

Everything is kernel-clean (no `sorry`/`axiom`/`native_decide`/`@[implemented_by]`).
-/

namespace QutritEis
open Eis

/-! ## Decidable divisibility by `λ₃` -/

/-- Decidable parity criterion for divisibility by `λ₃ = 1 - ω`: `3 ∣ (re + im)`. -/
def dvdLam (z : Eis) : Prop := (3 : ℤ) ∣ (z.re + z.im)

instance (z : Eis) : Decidable (dvdLam z) := by unfold dvdLam; infer_instance

/-- Explicit multiplication by `λ₃`: `λ₃·(p + qω) = (p + q) + (2q - p)ω`. -/
theorem lam_mul (w : Eis) : lam * w = ⟨w.re + w.im, 2 * w.im - w.re⟩ := by
  apply Eis.ext'
  · simp [lam]
  · simp [lam]; ring

/-- The parity criterion `dvdLam` is equivalent to honest divisibility by `λ₃`. -/
theorem dvdLam_iff (z : Eis) : dvdLam z ↔ lam ∣ z := by
  constructor
  · rintro ⟨k, hk⟩
    -- q = (re + im)/3, p = re - q ; then λ₃·(p + qω) = z
    refine ⟨⟨z.re - k, k⟩, ?_⟩
    rw [lam_mul]
    apply Eis.ext'
    · simp
    · simp; omega
  · rintro ⟨w, rfl⟩
    rw [lam_mul]
    exact ⟨w.im, by simp; ring⟩

/-! ## The lattice -/

/-- Scalar action of `ℤ[ω]` on `ℤ[ω]²`. -/
def vsmul (r : Eis) (v : Eis × Eis) : Eis × Eis := (r * v.1, r * v.2)

@[simp] theorem vsmul_fst (r : Eis) (v : Eis × Eis) : (vsmul r v).1 = r * v.1 := rfl
@[simp] theorem vsmul_snd (r : Eis) (v : Eis × Eis) : (vsmul r v).2 = r * v.2 := rfl

/-- Membership in the qutrit Barnes–Wall lattice `L = {(x,y) : λ₃ ∣ (x+y)}`. -/
def inL (v : Eis × Eis) : Prop := lam ∣ (v.1 + v.2)

instance : DecidablePred inL := fun v =>
  decidable_of_iff (dvdLam (v.1 + v.2)) (dvdLam_iff _)

theorem inL_iff (v : Eis × Eis) : inL v ↔ dvdLam (v.1 + v.2) := (dvdLam_iff _).symm

theorem inL_zero : inL (0, 0) := by simp [inL]

theorem inL_add {v w : Eis × Eis} (hv : inL v) (hw : inL w) :
    inL (v.1 + w.1, v.2 + w.2) := by
  unfold inL at *
  have : (v.1 + w.1) + (v.2 + w.2) = (v.1 + v.2) + (w.1 + w.2) := by ring
  rw [this]; exact Dvd.dvd.add hv hw

theorem inL_vsmul (r : Eis) {v : Eis × Eis} (hv : inL v) : inL (vsmul r v) := by
  unfold inL vsmul at *
  simp only
  have : r * v.1 + r * v.2 = r * (v.1 + v.2) := by ring
  rw [this]; exact Dvd.dvd.mul_left hv r

/-! ## Generators -/

/-- First generator `(1, -1)`. -/
def g1 : Eis × Eis := (1, -1)
/-- Second generator `(0, λ₃)`. -/
def g2 : Eis × Eis := (0, lam)

theorem inL_g1 : inL g1 := by decide
theorem inL_g2 : inL g2 := by decide

/-- Pairwise addition of column vectors. -/
def vadd (v w : Eis × Eis) : Eis × Eis := (v.1 + w.1, v.2 + w.2)

@[simp] theorem vadd_fst (v w : Eis × Eis) : (vadd v w).1 = v.1 + w.1 := rfl
@[simp] theorem vadd_snd (v w : Eis × Eis) : (vadd v w).2 = v.2 + w.2 := rfl

/-- Every lattice vector decomposes over the two generators. -/
theorem inL_decompose {v : Eis × Eis} (hv : inL v) :
    ∃ k : Eis, v = vadd (vsmul v.1 g1) (vsmul k g2) := by
  obtain ⟨k, hk⟩ := hv
  obtain ⟨x, y⟩ := v
  have hk' : x + y = lam * k := hk
  refine ⟨k, ?_⟩
  simp only [vadd, vsmul, g1, g2, Prod.mk.injEq]
  constructor
  · ring
  · linear_combination hk'

/-! ## `2×2` matrices over `ℤ[ω]` and their action -/

/-- A `2×2` matrix over `ℤ[ω]`. -/
structure EMat2 where
  a : Eis
  b : Eis
  c : Eis
  d : Eis
deriving DecidableEq, Repr

namespace EMat2

@[ext] theorem ext' {M N : EMat2} (ha : M.a = N.a) (hb : M.b = N.b)
    (hc : M.c = N.c) (hd : M.d = N.d) : M = N := by
  cases M; cases N; simp_all

/-- Matrix-vector product. -/
def mulVec (M : EMat2) (v : Eis × Eis) : Eis × Eis :=
  (M.a * v.1 + M.b * v.2, M.c * v.1 + M.d * v.2)

/-- Scalar multiple of a matrix. -/
def smul (r : Eis) (M : EMat2) : EMat2 := ⟨r * M.a, r * M.b, r * M.c, r * M.d⟩

@[simp] theorem mulVec_fst (M : EMat2) (v : Eis × Eis) :
    (M.mulVec v).1 = M.a * v.1 + M.b * v.2 := rfl
@[simp] theorem mulVec_snd (M : EMat2) (v : Eis × Eis) :
    (M.mulVec v).2 = M.c * v.1 + M.d * v.2 := rfl

theorem mulVec_add (M : EMat2) (v w : Eis × Eis) :
    M.mulVec (vadd v w) = vadd (M.mulVec v) (M.mulVec w) := by
  simp [mulVec, vadd]; constructor <;> ring

theorem mulVec_vsmul (M : EMat2) (r : Eis) (v : Eis × Eis) :
    M.mulVec (vsmul r v) = vsmul r (M.mulVec v) := by
  simp [mulVec, vsmul]; constructor <;> ring

@[simp] theorem smul_mulVec (r : Eis) (M : EMat2) (v : Eis × Eis) :
    (smul r M).mulVec v = vsmul r (M.mulVec v) := by
  simp [smul, mulVec, vsmul]; constructor <;> ring

@[simp] theorem smul_one_mat (M : EMat2) : smul 1 M = M := by cases M; simp [smul]

end EMat2

/-- An operator maps `L` into `L`. -/
def MapsToL (M : EMat2) : Prop := ∀ v, inL v → inL (M.mulVec v)

/-- **Reduction lemma.** A matrix preserves `L` iff it preserves both generators. -/
theorem mapsToL_of_gens (M : EMat2)
    (h1 : inL (M.mulVec g1)) (h2 : inL (M.mulVec g2)) : MapsToL M := by
  intro v hv
  obtain ⟨k, hk⟩ := inL_decompose hv
  rw [hk, EMat2.mulVec_add, EMat2.mulVec_vsmul, EMat2.mulVec_vsmul]
  exact inL_add (inL_vsmul _ h1) (inL_vsmul _ h2)

theorem mapsToL_smul (r : Eis) {M : EMat2} (h : MapsToL M) : MapsToL (EMat2.smul r M) := by
  intro v hv
  rw [EMat2.smul_mulVec]
  exact inL_vsmul r (h v hv)

/-! ## The grade -/

/-- `gradeLE M k`: the operator `λ₃^k · M` maps `L` into `L`. -/
def gradeLE (M : EMat2) (k : ℕ) : Prop := MapsToL (EMat2.smul (lam ^ k) M)

theorem gradeLE_succ {M : EMat2} {k : ℕ} (h : gradeLE M k) : gradeLE M (k + 1) := by
  unfold gradeLE at *
  have hpow : (lam ^ (k + 1)) = lam * lam ^ k := by ring
  rw [hpow]
  intro v hv
  rw [show EMat2.smul (lam * lam ^ k) M = EMat2.smul lam (EMat2.smul (lam ^ k) M) by
    cases M; simp [EMat2.smul]; refine ⟨?_, ?_, ?_, ?_⟩ <;> ring]
  exact mapsToL_smul lam h v hv

/-- The grade `g(M) = min k with λ₃^k·M·L ⊆ L`. -/
noncomputable def gradeEMat (M : EMat2) : ℕ := sInf {k | gradeLE M k}

theorem gradeEMat_le {M : EMat2} {k : ℕ} (h : gradeLE M k) : gradeEMat M ≤ k :=
  Nat.sInf_le h

theorem gradeEMat_eq_zero {M : EMat2} (h0 : gradeLE M 0) : gradeEMat M = 0 :=
  Nat.le_zero.mp (Nat.sInf_le h0)

theorem gradeEMat_eq_one {M : EMat2} (h1 : gradeLE M 1) (h0 : ¬ gradeLE M 0) :
    gradeEMat M = 1 := by
  have hmem : gradeEMat M ∈ {k | gradeLE M k} := Nat.sInf_mem ⟨1, h1⟩
  rcases Nat.lt_or_ge (gradeEMat M) 1 with h | h
  · interval_cases (gradeEMat M)
    · exact absurd hmem h0
  · exact le_antisymm (Nat.sInf_le h1) h

/-! ## Named diagonal operators and their grades -/

/-- The identity matrix. -/
def II : EMat2 := ⟨1, 0, 0, 1⟩
/-- `diag(1, ω)`. -/
def diagOmega : EMat2 := ⟨1, 0, 0, omega⟩
/-- `diag(1, -1)`. -/
def diagNegOne : EMat2 := ⟨1, 0, 0, -1⟩

/-- `diag(1, ω) ≡ I (mod λ₃)` preserves `L`: grade `0`. -/
theorem diagOmega_gradeLE_zero : gradeLE diagOmega 0 := by
  unfold gradeLE
  simp only [pow_zero, EMat2.smul_one_mat]
  apply mapsToL_of_gens <;> decide

theorem gradeEMat_diag_omega : gradeEMat diagOmega = 0 :=
  gradeEMat_eq_zero diagOmega_gradeLE_zero

/-- `diag(1, -1)` does NOT preserve `L`: it sends `(1,-1) ∈ L` to `(1,1) ∉ L`. -/
theorem diagNegOne_not_gradeLE_zero : ¬ gradeLE diagNegOne 0 := by
  intro h
  have h1 : inL ((1 : Eis), (-1 : Eis)) := by decide
  have := h ((1 : Eis), (-1 : Eis)) (by simpa using h1)
  revert this
  decide

theorem diagNegOne_gradeLE_one : gradeLE diagNegOne 1 := by
  unfold gradeLE
  apply mapsToL_of_gens <;> decide

/-- **`diag(1, -1)` has grade `1`** over the Eisenstein lattice. -/
theorem gradeEMat_diag_negOne : gradeEMat diagNegOne = 1 :=
  gradeEMat_eq_one diagNegOne_gradeLE_one diagNegOne_not_gradeLE_zero

end QutritEis
